### PR TITLE
[PowerToys] Run: Update for delay search setting

### PR DESCRIPTION
**Pull request by jaimecbernardo**
Update docs for the new setting introduced in https://github.com/microsoft/PowerToys/pull/18724

Please don't merge before the release of PT v0.59.1, which should happen shortly.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@jaimecbernardo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jaimecbernardo** [comment]
Hi @mattwojo ,
Could you please add @htcfreek  and @crutkas  as reviewers?
I think I'm unable to.
Thank you, in advance.

**Comment by ShannonLeavitt** [comment]
@mattwojo - Can you review the proposed changes? IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger7** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Review by crutkas — APPROVED** [review]

**Comment by crutkas** [comment]
Approved, this fix can go live later today

**Comment by ShannonLeavitt** [comment]
@crutkas - Thanks for approving the PR. For future PRs, please note that a `#sign-off` comment is the best way to signal to the review team that a PR is ready to merge. A PR approval doesn't push PRs into our queues for processing.

**Review by htcfreek — APPROVED** [review]

**Pull request merged**
