### PR TITLE
Wrap long line in commanding example

### PR DESCRIPTION
**Pull request by AtosNicoS**
This fix avoids annoying vertical scrolling on the documentation:
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/commanding

### CODE REVIEW

**Comment by PRMerger20** [comment]
@AtosNicoS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]
@AtosNicoS - thanks for catching and correcting this!

**Comment by Jak-MS** [comment]
will re-check this after the CLA check has completed. it can take a long time on first submit.

meanwhile, i'll close and reopen to see if that unsticks it.

**Comment by ktoliver** [comment]
@AtosNicoS - Could you try again to sign the CLA? Thank you.

**Comment by AtosNicoS** [comment]
Please fix this simple typo yourself, I will not sign any CLA.

**Comment by Jak-MS** [comment]
@Karl-Bridge-Microsoft - we're closing this PR since we can't accept the changes without the contributor's signed and approved CLA.  If you want to make changes to the article, can you open a new PR? Thanks.

**Pull request closed without merging**
