### PR TITLE
Merge Dev Home docs

### PR DESCRIPTION
**Pull request by skanda890**

### CODE REVIEW

**Review by skanda890 — COMMENTED** [review]
Merge this.

**Comment by skanda890** [comment]
@microsoft-github-policy-service agree

**Comment by skanda890** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by mattwojo** [comment]
Hi @skanda890 - It looks like maybe this PR was filed by mistake (?). If I'm wrong, please feel welcome to reopen with a description of what you're trying to update.

**Comment by skanda890** [comment]
I was trying to do this in my forked Dev Home repository, but why and how did I create a pull request here?

**Pull request closed without merging**
