### PR TITLE
Update uno-setup.md

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by Jak-MS** [comment]
@alvinashcraft 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.

NOTE: the metadata should be restored. Include files should also have the following metadata: 
image


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by alvinashcraft** [comment]
@Jak-MS Can you check the private repo? This conflicts with a PR I just completed today to add the metadata.

**Comment by Youssef1313** [comment]
@alvinashcraft I'm okay to wait until your PR flows to this repo, and then I'll resolve any conflicts.

**Comment by alvinashcraft** [comment]
Sounds good. The changes look good to me, so I'll review and sign off once the private changes are merged here. Thanks!

**Review by lukeblevins — APPROVED** [review]

**Comment by ShannonLeavitt** [comment]
Note: The metadata appears in the [include file in the private repo](https://github.com/MicrosoftDocs/windows-dev-docs-pr/blob/main/hub/includes/uno-setup.md).

**Review by alvinashcraft — APPROVED** [review]
I'll sign off on this now. The changes in the private repo don't touch any of the same lines, so it shouldn't be a problem merging them.

**Comment by alvinashcraft** [comment]
#sign-off

**Pull request merged**
