### PR TITLE
Update docs for PowerToys/ShortcutGuide

### PR DESCRIPTION
**Pull request by OkamiWong**
In accordance with https://github.com/microsoft/PowerToys/pull/21762

### CODE REVIEW

**Comment by mattwojo** [comment]
Looks like https://github.com/microsoft/PowerToys/pull/21762 isn't merged in yet so marking this as "Needs more info" until it's in the live branch. 
Also, I'm not sure that calling this "global Windows shortcuts or taskbar icon shortcuts" vs "Shortcut Guide" is better for the user as that title doesn't seem to be defined anywhere. (?) Also looks like the tool calls it "duration" rather than "durations" -- screenshot update is good though! So many more tools being added! :)

**Comment by OkamiWong** [comment]
@mattwojo Thanks for taking a look! Shall we remove the text changes and only keep the screenshot update? I don't have any other better phrasing in my mind currently.

**Comment by OkamiWong** [comment]
@mattwojo https://github.com/microsoft/PowerToys/pull/21762 is merged. If you have any idea on improving the phrasing, please let me know and I can update it.

**Comment by Jay-o-Way** [comment]
> "global Windows shortcuts or taskbar icon shortcuts"

These words were my idea, one _thing_ got split into two _things_ now. But if there are better words, be my guest. Having that said: plural "durations" sounds appropriate to me.

**Comment by Jay-o-Way** [comment]
Anything keeing this?

**Comment by OkamiWong** [comment]
@mattwojo Hi there, is there any action we can take about this PR?

**Comment by mattwojo** [comment]
Thanks for the reminder - merging!

**Pull request merged**
