### PR TITLE
Update bluetooth-dev-faq.md

### PR DESCRIPTION
**Pull request by sergio-re**
Excellent documentation, however some points were not clear. I made some grammar corrections, clarified some sentences  and changed wording from informal speech to more formal techincal documentation.

Sergio J. Re
Sr. PFE 
Microsoft Corporation
sergior@microsoft.com

### CODE REVIEW

**Comment by garycentric** [comment]
@eliotcowley  : The PR **passed** the acceptance checklist. Please evaluate further and approve/complete the PR if appropriate. Thanks!

**Comment by PRMerger12** [comment]
@sergio-re : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@eliotcowley : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by eliotcowley — APPROVED** [review]

**Comment by eliotcowley** [comment]
Thanks @sergio-re, I've merged your changes and they should be live soon.

**Pull request merged**
