### PR TITLE
Mary advanced visibility option

### PR DESCRIPTION
**Pull request by marmuc680**
Hi-

Added a new file, the images/screenshots are are not showing in the article. Please help me figure that out.

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @marmuc680 - Thank you for your contribution. Would you take a moment to sign the CLA? After the CLA is signed, we can process the pull request. Thanks.

**Comment by PRMerger15** [comment]
@marmuc680 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
We've assigned this PR to @hickeys per Teams.

The new content will need to be moved to the private repo before merging for automated validations, Acrolinx, staging, and full PR review. The PR review team can move the commit when it's complete and approved by the content team.

To maintain quality and support the internal build process, new content needs to meet the [PR review quality criteria](https://review.docs.microsoft.com/help/contribute/contribute-how-to-write-pull-request-quality-criteria?branch=master); this is validated in the private repo. Thanks.

**Comment by marmuc680** [comment]
Hi -
This work item is high priority, the PM owner has a deadline of today, is there a possibility we can review this sooner?

**Comment by ktoliver** [comment]
@marmuc680 Hi, I'll move the commit to the private repo and make some basic formatting fixes. Someone from the content team (a SME) will need to review the content and sign off. I'll post the new PR # here shortly, and then close this PR.

**Comment by ktoliver** [comment]
@marmuc680 Is the article supposed to be in the **windows-apps-src/publish/** folder?

Here: https://github.com/MicrosoftDocs/windows-uwp-pr/tree/master/windows-apps-src/publish ?

**Comment by ktoliver** [comment]
The new PR number in the private repo is https://github.com/MicrosoftDocs/windows-uwp-pr/pull/949. We'll close this PR.

**Comment by marmuc680** [comment]
@ktoliver ; I thought I created this on my private branch, what do I need to do at this point?

**Comment by ktoliver** [comment]
@marmuc680 I moved the commit from your branch to my working branch in the private repo by using a series of Git commands. If you complete the steps in [Join the MicrosoftDocs organization](https://review.docs.microsoft.com/help/contribute/contribute-get-started-setup-github?branch=master#join-microsoftdocs-organization-and-others)--it's just a few clicks--you should be able to see the new PR in the private repo. The status of the PR is that it is assigned to @hickeys for review.

**Comment by marmuc680** [comment]
@ktoliver got it! thank you.

**Pull request closed without merging**
