### PR TITLE
Fixed typo.

### PR DESCRIPTION
**Pull request by tim-weis**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@tim-weis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@tim-weis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@tim-weis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@tim-weis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@tim-weis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by jwmsft — APPROVED** [review]

**Comment by jwmsft** [comment]
@tim-weis, thanks for submitting these fixes.

#sign-off

**Pull request merged**
