### PR TITLE
Thomasclaudiushuber update winui3 desktop

### PR DESCRIPTION
**Pull request by thomasclaudiushuber**
Fixes issue #2819

### CODE REVIEW

**Comment by PRMerger20** [comment]
@thomasclaudiushuber : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mcleanbyron** [comment]
Thanks for your pull request. I already made similar updates to the docs per your issue at https://github.com/MicrosoftDocs/windows-uwp/issues/2819, so I am closing this pull request.

**Comment by thomasclaudiushuber** [comment]
Thank you @mcleanbyron, looks perfect what you did there!

**Pull request closed without merging**
