### PR TITLE
PT Run: Update RB command on SysPlugin section

### PR DESCRIPTION
**Pull request by htcfreek**
This is the docs PR for the changes in microsoft/PowerToys#23045.

**Please don't merge after the change is released and @crutkas or @jaimecbernardo  approved this docs PR.**

### CODE REVIEW

**Comment by crutkas** [comment]
Chances are this would be merged in start of Feb 2023 (0.67 release) due to time the PR hit powertoys. High chance the main PR will miss the 0.66 release.

**Comment by htcfreek** [comment]
Target release is 0.67 in start of Feb 2023.

ping: @crutkas , @jaimecbernardo , @stefansjfw

**Review by jaimecbernardo — APPROVED** [review]
LGTM! Thank you for updating the docs!

**Comment by jaimecbernardo** [comment]
@mattwojo , PowerToys 0.67.0 has been released, so this can be merged. Thank you!

**Pull request merged**
