### PR TITLE
Updated group policy docs and picture of File Explorer page

### PR DESCRIPTION
**Pull request by acekirkpatrick**
This is for the group policy changes in [PowerToys #33475](https://github.com/microsoft/PowerToys/pull/33475).
I also updated the screenshot for File Explorer to show the new toggle switch.
#
### Please don't merge before:
- A review from the PowerToys core maintainers.
- The release of PowerToys 0.83.0.
- microsoft/PowerToys/pull/33475 to merge.

### CODE REVIEW

**Review by alvinashcraft — APPROVED** [review]
This looks good. We'll hold it until the release goes live. Thanks!

**Comment by htcfreek** [comment]
The new image cuts off the Thumbnail Preview part of the settings page. For a good overview about the module we should not do this. @acekirkpatrick can you update the new image?

**Review by alvinashcraft — APPROVED** [review]
Thanks for updating the screenshot to include the entire screen!

**Comment by htcfreek** [comment]
@alvinashcraft 
Can you plz revert this commit. The feature/changes were not merged for the 0.83.0 release. They will be in the 0.84.0 release in August/September.

**Comment by alvinashcraft** [comment]
> @alvinashcraft Can you plz revert this commit. The feature/changes were not merged for the 0.83.0 release. They will be in the 0.84.0 release in August/September.

Will do. On it now.

**Comment by alvinashcraft** [comment]
@htcfreek Revert PR merged in private repo. It should sync to the public repo and live site in a few minutes. Thanks for the heads-up.

**Comment by htcfreek** [comment]
Do we need a new PR from @acekirkpatrick to update the docs if it is implemented in PowerToys then?

**Comment by alvinashcraft** [comment]
Yes, we'll need another PR to re-commit the changes in the next release.

**Pull request merged**
