### PR TITLE
v0.49 Update

### PR DESCRIPTION
**Pull request by dedavis6797**
New Mouse utilities

New PowerRename UI

Video Conference Mute no longer experimental

### CODE REVIEW

**Comment by PRMerger15** [comment]
@dedavis6797 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dedavis6797** [comment]
cc: @mattwojo

**Comment by PRMerger10** [comment]
@dedavis6797 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@dedavis6797 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@dedavis6797 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger5** [comment]
@dedavis6797 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
