### PR TITLE
[PowerToys] Update PT Run page for PT v0.77.0

### PR DESCRIPTION
**Pull request by htcfreek**
- Some page improvements including links to se plugin sections.
- Updated docs for the Value Generator plugin.

---

### Please do not merge before:
- The release of PowerToys `0.77.0` in January 2024.
-  microsoft/PowerToys/pull/30648 is merged.
- An approval of @jaimecbernardo or @crutkas .

### CODE REVIEW

**Comment by htcfreek** [comment]
@alvinashcraft 
I have converted the PR to draft to prevent auto-merge.

**Comment by alvinashcraft** [comment]
[like]  Alvin Ashcraft reacted to your message:
________________________________

**Review by alvinashcraft — APPROVED** [review]
Looks good. I'll hold on to this until the release is ready. Ping me if you have any additional changes in the meantime. Thanks!

**Comment by htcfreek** [comment]
@alvinashcraft
FYI: The new feature will be part of PT `0.77.0` in January. I updated the PR title and description.

**Comment by alvinashcraft** [comment]
> @alvinashcraft FYI: The new feature will be part of PT `0.77.0` in January. I updated the PR title and description.

Thanks for the heads-up. It looks like we have one other docs PR for 0.77.0 right now. I'll merge them both when it goes live.

**Pull request merged**
