### PR TITLE
Update create-a-basic-windows-10-app-in-cpp.md

### PR DESCRIPTION
**Pull request by jaigak**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@Jaiganeshkumaran : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ktoliver** [comment]
@QuinnRadich For review. Thanks.

**Review by QuinnRadich — APPROVED** [review]

**Comment by QuinnRadich** [comment]
This page has been updated parallel to this PR, and thus it's no longer needed.

**Pull request closed without merging**
