### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by asklar**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@asklar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@stevewhims 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by PRMerger12** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]

**Comment by stevewhims** [comment]
Few tweaks:

It feels like when listing platforms, we ought to mention the most important (recommended/supported) one first.
I wanted to add a link to the Windows App SDK content from here.
And it has been discussed that there really aren't Windows App SDK apps (or at least the term/concept is inelegant/misleading). Rather there are WinUI 3 apps, WPF apps, etc (all different kinds of desktop apps) that use the Windows App SDK. So I changed it to that.

**Comment by asklar** [comment]
thanks @stevewhims ! 😊

**Pull request merged**
