### PR TITLE
[PowerToys] Aligned installation requirements

### PR DESCRIPTION
**Pull request by davidegiacometti**
- Changed arm to ARM64
- Aligned requirements to latest version: Windows 10 increased to 2004 with 0.60.0 release

### CODE REVIEW

**Comment by PRMerger8** [comment]
@davidegiacometti : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@mattwojo 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger14** [comment]
@mattwojo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattwojo** [comment]
@crutkas - Could you take a look at these updates and give a thumbs up to merge if all looks good?

**Review by crutkas — APPROVED** [review]

**Comment by crutkas** [comment]
ship it

**Pull request merged**
