### PR TITLE
Removed references to webpush

### PR DESCRIPTION
**Pull request by manoskow**
This doc is confusing for developers, and makes it seem like an alternative way to send notifications. This is pretty difficult to implement and is intended mostly for web browsers that are hosting websites and their notifications.  Trying to eliminate some of this confusion.

### CODE REVIEW

**Comment by garycentric** [comment]
PRRT: review required.

@mijacobs : The PR **passed** the acceptance checklist. Please evaluate further and approve/complete the PR if appropriate. Thanks!

**Comment by PRMerger12** [comment]
@manoskow : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by mijacobs — APPROVED** [review]

**Comment by mijacobs** [comment]
#signoff

**Comment by mijacobs** [comment]
#sign-off

**Pull request merged**
