### PR TITLE
Add F#

### PR DESCRIPTION
**Pull request by avestura**
Add F# to get started docs

### CODE REVIEW

**Comment by PRMerger15** [comment]
@avestura : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattwojo** [comment]
Thanks for this contribution @avestura. I have a couple of other updates/additions that I need to make to this landing page, so I am going to hold off on merging it in until I can update the layout as a whole, but I think adding F# will be a good addition. Thanks again.

**Review by mattwojo — APPROVED** [review]

**Comment by PRMerger5** [comment]
@mattwojo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@mattwojo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by mattwojo — APPROVED** [review]

**Pull request merged**
