### PR TITLE
Update how-to-launch-an-app-for-results.md

### PR DESCRIPTION
**Pull request by jamienhare**
Added a cppwinrt code snippet option for steps 1-5

### CODE REVIEW

**Comment by jamienhare** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by Court72** [comment]
@jamienhare

Thank you for your contribution. Would you take a moment to sign the [Contributor License Agreement (CLA)](https://github.com/MicrosoftDocs/windows-dev-docs/pull/4441#issuecomment-1562081052)? After the CLA is signed, someone can review your pull request. Thanks!

(Note: Remove the `>` from [your comment](https://github.com/MicrosoftDocs/windows-dev-docs/pull/4441#issuecomment-1562081929), and it should work)

**Comment by Court72** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by alvinashcraft — APPROVED** [review]
Thanks for adding the cppwinrt samples! This is fantastic, and it really improves the docs.

**Pull request merged**
