### PR TITLE
Updated PowerToys docs

### PR DESCRIPTION
**Pull request by Jay-o-Way**
Fixes https://github.com/microsoft/PowerToys/issues/11793
Fixes https://github.com/microsoft/PowerToys/issues/11514
Fixes https://github.com/microsoft/PowerToys/issues/10810
Fixes https://github.com/microsoft/PowerToys/issues/12358
Fixes https://github.com/microsoft/PowerToys/issues/10974

Mainly focused on `<kbd>` tags, added some text about hotkeys and text fixes. (No need to wait for the release of next version)
@dedavis6797 @crutkas

### CODE REVIEW

**Comment by PRMerger19** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dedavis6797** [comment]
@Jay-o-Way thank you for this PR. These updates look awesome, and really help improve the clarity/conciseness of the PowerToys documentation! We'll follow-up on subsequent adjustments, but given the size of the current PR, we should go ahead and merge this in. 

@mattwojo I looked it over and this looks good to go!

**Comment by mattwojo** [comment]
Thanks @Jay-o-Way!! Merging! 🥇

**Pull request merged**
