### PR TITLE
improved docs

### PR DESCRIPTION
**Pull request by Sundaran13**

### CODE REVIEW

**Comment by ktoliver** [comment]
@GrantMeStrength Could you review the proposed change to the repo README file? I would leave as-is because as the content owner and source, Microsoft might not be considered a contributor. (The same clause appears elsewhere in the file.) But your team can make the determination. Thanks!

**Comment by paramat** [comment]
See author's GitHub activity, this seems to be a 'hacktoberfest' spam PR.
See https://hacktoberfest.digitalocean.com/details#spam for how to label it to disqualify it.

**Comment by ktoliver** [comment]
Thanks @paramat. 

I'll ask the repo owners to make the call -- @GrantMeStrength @mijacobs

Thanks!

**Comment by GrantMeStrength** [comment]
Thanks, but we shouldn't randomly add words to the legal text on topics.

**Pull request closed without merging**
