### PR TITLE
Update perfview download links

### PR DESCRIPTION
**Pull request by gewarren**
(Hide whitespace changes in diff - my editor cleans up whitespace automatically.)

### CODE REVIEW

**Comment by gewarren** [comment]
#sign-off

**Review by stevewhims — CHANGES_REQUESTED** [review]
This doesn't look correct:

`from the [Microsoft Download Center](https://github.com/Microsoft/perfview/releases)`

Does that link text need changing?

**Comment by stevewhims** [comment]
How do you hide whitespace changes? I hunted around for it for a while, but then it became quicker just to scroll past the whitespace changes. :) UPDATE: Oh, I found it. Never needed that setting before.

Microsoft FTEs are encouraged to use private repos, by the way. So the one to use would be https://github.com/MicrosoftDocs/windows-dev-docs-pr.

Thanks!
-Steve

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Review by stevewhims — APPROVED** [review]
I'll take the liberty of approving (and merging) on behalf of Karl, too. :) [Oh, he already approved.] :)

**Comment by gewarren** [comment]
Thank you!

**Pull request merged**
