### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by jaigak**
Fixes a few statements that misleads developers.
- WinRT isn't a managed runtime environment.
- UWP XAML != UWP although UWP XAML is the most preferred choice for UWP UI.
- Fluent Design System is only available built-in for UWP apps when using XAML.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@Jaiganeshkumaran : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Jaiganeshkumaran : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ktoliver** [comment]
@QuinnRadich Could you review the proposed changes? Merge conflicts will be tricky to resolve; if the section move is approved, it might be best to start with a fresh pull request and work with the current version in the default branch.

**Comment by Jay-o-Way** [comment]
@QuinnRadich ping

**Comment by QuinnRadich** [comment]
This PR was significantly delayed (and got left behind a bit, apologies) when we were making other revisions to this page. While I'm sorry it took so long to address it, it's no longer aligned to the current state of the page. There's one tweak here (referring to the wording around managed runtime environments) that I'll carry over outside of this PR.

**Pull request closed without merging**
