### PR TITLE
Power toys v0.41 Updates

### PR DESCRIPTION
**Pull request by dedavis6797**
@mattwojo please help us get this checked in by 6/28 EOD if possible.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@dedavis6797 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@dedavis6797 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by mattwojo — CHANGES_REQUESTED** [review]
powertoys-espresso-tray.gif and powertoys-espresso.png image file names should be updated to reflect the new tool name (espresso > awake)

**Comment by PRMerger12** [comment]
@dedavis6797 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@mattwojo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@mattwojo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@mattwojo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by mattwojo — APPROVED** [review]

**Pull request merged**
