### PR TITLE
Update credential-locker.md

### PR DESCRIPTION
**Pull request by shweaver-MSFT**
Adding some additional info about the CredentialLocker after a recent engagement with an external partner developing a UWA.

### CODE REVIEW

**Comment by mikematteson** [comment]
Hi @shweaver-MSFT: Thanks for your contribution. Going forward, CX asks that Microsoft employees use VSTS to submit documentation changes. Future contributions via GitHub will be closed with a request that you resubmit them via VSTS. More information is at http://aka.ms/windowsauthoring (see **UWP instructions** > **Conceptual content**).

**Comment by mikematteson** [comment]
@awkoren: This contribution **passed** the PR checklist. Please review further and merge if appropriate.

**Review by awkoren — APPROVED** [review]

**Comment by shweaver-MSFT** [comment]
@mikematteson @awkoren I don't mean to be difficult, but I followed the guidance from the [UWP instructions > Conceptual content](https://cpubwin.visualstudio.com/_git/windows-uwp?path=%2FCONTRIBUTING.md&version=GBmaster&_a=preview) page:

> If you are a Microsoft employee, you can work in either the public repo or the private content repository.

> Editing topics on the public repo
We've tried to make editing an existing file as simple as possible.

> * If you're already in the repo, just navigate to the file and click the Edit button.
> * Alternatively, if you're viewing a Docs.microsoft.com page in your browser, click the Edit button on the top right of the page. You will be redirected to the correct Markdown source file in the repo, where you can click the Edit button.

> GitHub automatically forks the official repo into your personal GitHub account, where you can make your changes. When you're done, submit a pull request back to the "docs" branch. After you create the pull request, a member of the UWP Documentation team will review your changes. If your request is accepted, updates are published to https://docs.microsoft.com/windows/.

Has this guidance changed? If so... please update the doc ;)

**Comment by mikematteson** [comment]
@shweaver-MSFT -- Sincere apologies for the conflicting messages. I thought we had cleared this up in the guidance. I'll go sort it out shortly. Thanks.

Cc: @awkoren

**Comment by shweaver-MSFT** [comment]
Much appreciated :)

**Pull request merged**
