### PR TITLE
[PowerToys] [Docs] Updated settings images

### PR DESCRIPTION
**Pull request by niels9001**
@dedavis6797 @crutkas FYI

Fixes: https://github.com/microsoft/PowerToys/issues/12816

### CODE REVIEW

**Comment by PRMerger9** [comment]
@niels9001 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@niels9001 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dedavis6797** [comment]
It looks like we still need to update pt-keyboard-manager.png for the index.md file, but other than these look awesome! Thank you @niels9001 for the fast turn-around on this.

@mattwojo this update is to be included in our v0.45 release which is slated for Tuesday next week. Once pt-keyboard-manager.png is updated we can merge this in on 8/31.

**Comment by PRMerger12** [comment]
@niels9001 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by niels9001** [comment]
> It looks like we still need to update pt-keyboard-manager.png for the index.md file, but other than these look awesome! Thank you @niels9001 for the fast turn-around on this.

Ah yes, good catch. Updated the KBM and Awake images so this should be good to go once 0.45 rolls out!

**Pull request merged**
