### PR TITLE
Update instructions and code segment

### PR DESCRIPTION
**Pull request by capegreg**
Add instruction no elevated VS2019
ref discussion: https://github.com/microsoft/WindowsAppSDK/discussions/1320

Clear ambiguous using ResourceManager

### CODE REVIEW

**Comment by PRMerger15** [comment]
@capegreg : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AdamBraden** [comment]
LGTM

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger5** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Merging with PM @AdamBraden approval. Thanks.

**Review by mbfaust19 — COMMENTED** [review]
thanks

**Pull request merged**
