### PR TITLE
Fix Typo and Unexpected character

### PR DESCRIPTION
**Pull request by ghost1372**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@ghost1372 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@ghost1372 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rkarman** [comment]
Thanks for catching! I already have a PR out for the unexpected backticks in the text but missed the typo.

**Review by rkarman — APPROVED** [review]

**Comment by PRMerger17** [comment]
@ghost1372 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by rkarman — APPROVED** [review]

**Review by jwmsft — APPROVED** [review]

**Comment by jwmsft** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@jwmsft: I'm sorry - only the author of this article, @rkarman, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
