### PR TITLE
update the icon details for quick reply text box

### PR DESCRIPTION
**Pull request by tfennel**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@tfennel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Comment by Jak-MS** [comment]
taking @Karl-Bridge-Microsoft sign off and approval.

**Pull request merged**
