### PR TITLE
Adding documentation for a new PowerToys tool - Awake

### PR DESCRIPTION
**Pull request by dend**
The tool is currently gated behind a pull request in the PowerToys repository: https://github.com/microsoft/PowerToys/pull/11245. Once it's merged, we will need to make sure that we have documentation available.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@dend : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@dend : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@mattwojo The pull request is in draft status, but note that these items will need to be resolved before merging:
- Add the new article to a TOC
- Ensure that complete metadata is used
- Add an image file for the image reference or delete the reference (ensure that the file name of an added image file aligns with the file naming standards that are defined in the internal contributor guide)

Thanks.
PR review team

**Comment by mattwojo** [comment]
@dend - do you have an image / screenshot that still needs to be added?

I can add to the TOC and add metadata.

@crutkas @dedavis6797 -- Could one or both of you please review and approve?

**Comment by dend** [comment]
@mattwojo not yet, this is still work in progress (hence the draft status of the PR 😊) - once ready, I will just ask you to review and add the metadata, since I am not sure what you want to track this as.

**Comment by PRMerger9** [comment]
@dend : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dend** [comment]
@crutkas @mattwojo flagging this for your review. This should include screenshots and TOC addition. Feel free to add the relevant metadata.

**Comment by ktoliver** [comment]
One more pull request review note: To promote SEO and to protect branding, the names of Microsoft products and services shouldn't be abbreviated in file names as unofficial or unapproved acronyms; suggest using "powertoys" instead of "pt" in image file names. Thanks!

**Comment by dend** [comment]
@ktoliver thank you for the feedback! The `pt-` abbreviation currently matches a number of other files in the repository:

image

Not opposed to changing the name, but bringing to light the broader change that needs to be made to the contents of the image folder.

**Comment by PRMerger12** [comment]
@dend : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@mattwojo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@mattwojo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattwojo** [comment]
pt-espresso-menu

Looks like I don't have permissions to add this image for the index page, @dend - could you put this in the hub/images folder please?

**Comment by dedavis6797** [comment]
@mattwojo I just added that image to my own branch which I cloned from this PR for general 0.39 updates. Once I get approval to submit it we can close this PR and just work with mine. Thanks for all your help @dend!

**Comment by mattwojo** [comment]
Thanks @dedavis6797 -- just let me know if there's anything further that you'd like me to review before this is merged in. Assuming this means that you will also coordinate the timing of the 0.39 update with the publishing of this doc.. if you'd like any assistance, just let me know.

**Comment by PRMerger17** [comment]
@dend : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@dend : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dend** [comment]
For the related engineering item: https://github.com/microsoft/PowerToys/pull/11593

**Comment by ktoliver** [comment]
@mattwojo Is this pull request ready for your final review? 

Thanks.

**Comment by crutkas** [comment]
Awake needs .41 to ship (aka monday)

**Comment by mattwojo** [comment]
Closing as this has been included in the 0.41 updates: https://github.com/MicrosoftDocs/windows-uwp/pull/3196

**Pull request closed without merging**
