### PR TITLE
Added C++ snippits to mica.md

### PR DESCRIPTION
**Pull request by Koyuki-of-SimpleIO**
Added C++ code snippits that are confirmed fully functional using VS 2022
Also added the header file includes

### CODE REVIEW

**Comment by PRMerger9** [comment]
@Koyuki-of-SimpleIO : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by sylveon** [comment]
Why C++/CX instead of C++/WinRT?

**Comment by Koyuki-of-SimpleIO** [comment]
> Why C++/CX instead of C++/WinRT?

Comfort mainly, have written in CX for a while. If you would like I can update the example to follow WinRT rules, but overall I really do prefer CX.

**Comment by sylveon** [comment]
It should be in cppwinrt, as C++/CX is deprecated and cppwinrt is recommend for all new development, so docs shouldn't be recommending it.

**Comment by Koyuki-of-SimpleIO** [comment]
Got it, will update to RT tonight.

**Review by hickeys — APPROVED** [review]
These look fine to me, but my c++ is rusty. I'm requesting a review from someone who knows the language much better than me.

**Review by stevewhims — CHANGES_REQUESTED** [review]
It was discussed in the conversation thread that this code needs porting from C++/CX to C++/WinRT. The thing is, if there is only ONE flavor of C++ in a topic then that flavor needs to be C++/WinRT. There's already a C# version of the code, so the topic meets the min bar for code examples. If I get bandwidth I'll be happy to port that existing C# version to C++/WinRT (and in fact it's often easier to go from C# to C++/WinRT than from C++/CX to C++/WinRT). But I'd recommend closing this PR, unless we can get it changed to C++/WinRT.

**Comment by stevewhims** [comment]
Oh, also the language slug needs a tweak. Since this is C++/CX (which we shouldn't publish) the slug for that is ```cppcx. But once it's ported to C++/WinRT, it'd be ```cppwinrt.

**Review by hickeys — APPROVED** [review]

**Comment by stevewhims** [comment]
This one is very old now, and isn't being actively worked from either side. Let's close it. Thanks, all! :)

-Steve

**Pull request closed without merging**
