### PR TITLE
Add some details in Xaml Islands articles

### PR DESCRIPTION
**Pull request by michalleptuch**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@michalleptuch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by michalleptuch** [comment]
I confirmed this issue: [Cannot Submit Xaml Island App to Microsoft Store](https://github.com/microsoft/microsoft-ui-xaml/issues/3488)

**Comment by mcleanbyron** [comment]
@marb2000 and @ocalvo - can you please review these proposed changes to the XAML Islands docs?

**Review by ocalvo — APPROVED** [review]

**Comment by ktoliver** [comment]
Hi @mcleanbyron When the updates are published, check that the left-aligned alerts (notes) don't interrupt consecutive numbering in the lists. To prevent this, the notes should be indented to align with the list items (to indent, select all lines that create the alert and press your tab key).
Thanks. (PR review team)

**Comment by mcleanbyron** [comment]
Thanks @ktoliver. I confirmed that the lists aren't interrupted, but I went ahead and fixed the indentations. Thanks for catching that.

**Review by marb2000 — COMMENTED** [review]
Looks good to me.

**Pull request merged**
