### PR TITLE
Update opening-a-developer-account.md

### PR DESCRIPTION
**Pull request by petand123**
Fixing a paragraph per Brenda's request in this task: https://microsoft.visualstudio.com/OSGS/_queries/edit/26439207/?triage=true

### CODE REVIEW

**Comment by PRMerger16** [comment]
@petand123 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @petand123 - This pull request was opened in the public repo; the content has a private repo. If you're set up to work in the private repo, could you close this PR and make the update in the private repo instead? Thanks!

**Comment by petand123** [comment]
Hi @ktoliver I'd be happy to but I'm not sure how. I've never worked in this repo and have just been requested to make this one fix, so Shawn sent me here. What do you suggest? Thanks!

**Comment by ktoliver** [comment]
> Hi @ktoliver Kristine Toliver (Aquent LLC) Vendor I'd be happy to but I'm not sure how. I've never worked in this repo and have just been requested to make this one fix, so Shawn sent me here. What do you suggest? Thanks!

Thanks @petand123. If @hickeys asked you to work in this repo, we'll leave this PR as it is. Thanks!

**Comment by petand123** [comment]
Hi, @ktoliver - thank you!

**Comment by hickeys** [comment]
@petand123 I think I sent you the wrong link. You should be using the private repo. Totally my fault, sorry. 

Not worth redoing this since it's good to go already, so I'll merge it. In the future, please ignore what I said and use the private repo 😅

**Pull request merged**
