### PR TITLE
Update PowerToys docs

### PR DESCRIPTION
**Pull request by Jay-o-Way**
Mostly focussed on tables and kbd tweaks.
See https://github.com/microsoft/PowerToys/issues/13165
FYI @dedavis6797

### CODE REVIEW

**Comment by PRMerger17** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@mattwojo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattwojo** [comment]
Thanks for all of these updates @Jay-o-Way! One note - we generally try to use the language of "select", rather than "click" or "press" in our docs in an effort to be more inclusive of users who may be using adaptive devices, but I'm approving for a merge with the current terms pending a conversation in the PowerToys dev meeting to see how folks feel this should be handled moving forward (as I'm not confident that I understand the full use-case picture in regard to PT). Everything else looks great. Thanks again!

**Comment by Jay-o-Way** [comment]
Oh I see. My thought was that "press" sounds more like an action and "select" sounds like "choose", which is not so much an action. Also used "press" in favor of "click" to include touch. But you're right, there are other input methods.

**Comment by mattwojo** [comment]
Totally makes sense.

**Pull request merged**
