### PR TITLE
Add extract parameter to file upload

### PR DESCRIPTION
**Pull request by develmusa**
The extract parameter is missing in the documentation although it is required.

### CODE REVIEW

**Comment by PRMerger5** [comment]
@develmusa : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ktoliver** [comment]
@Karl-Bridge-Microsoft - Could you review this proposed update to your article?

Thanks!

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by PRMerger12** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
