### PR TITLE
Update touch-interactions.md

### PR DESCRIPTION
**Pull request by nukeulis**
Remove triplicate entries and fix some content

### CODE REVIEW

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for your contribution! The changes you’ve made look good. To allow us to merge them with our documentation, we just need you to complete the Contribution License Agreement (CLA) at the link provided in the comment above (from msftclas, the Microsoft Pull Request Bot).

**Comment by mikematteson** [comment]
@nukeulis 
Checking in once more to ask that you complete the Contribution License Agreement (CLA) so we can go ahead and merge the changes you proposed. Thanks!

**Comment by nukeulis** [comment]
I think I did this already... can you send me a link?


________________________________

**Comment by mikematteson** [comment]
@nukeulis 
You did indeed sign it already; apologies for all the back-and-forth on this. I had to close and reopen the PR to get it to show the updated status--obviously a glitch somewhere on our side. We really appreciate both your contribution and your patience, and we'll get your changes on their way today.

**Comment by mikematteson** [comment]
@Karl-Bridge-Microsoft: All set! Please review and merge.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]
Updates look good! Thanks!

**Comment by nukeulis** [comment]
Thanks Mike,


No worries.


________________________________

**Pull request merged**
