### PR TITLE
Create Private-Audience-documentation.md

### PR DESCRIPTION
**Pull request by marmuc680**
don't merge this, the file is work in progress

### CODE REVIEW

**Comment by PRMerger19** [comment]
@marmuc680 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@marmuc680 I'll send you an email about [GitHub account setup](https://review.docs.microsoft.com/help/contribute/contribute-get-started-setup-github?branch=master) and working in GitHub as a Microsoft-internal contributor. Thanks!

**Comment by ktoliver** [comment]
#hold-off per contributor

**Comment by PRMerger12** [comment]
@marmuc680 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request closed without merging**
