### PR TITLE
Update Get started docs to Windows 11

### PR DESCRIPTION
**Pull request by noraa-junker**
Updates the get started docs and one image to Windows 11.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Aaron-Junker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger5** [comment]
@Aaron-Junker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger5** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger3** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @Aaron-Junker - A Microsoft Docs standard is to avoid publishing personal data in images. In **win10-cs-00.png**, in the upper-left corner, could you use an image editing app to cover/remove your name, email address, and profile photo? For example, what I would do in this case is cover it with a black square, to match the background. Then we can merge the pull request. Thanks!

**Comment by noraa-junker** [comment]
> Hi @Aaron-Junker - A Microsoft Docs standard is to avoid publishing personal data in images. In **win10-cs-00.png**, in the upper-left corner, could you use an image editing app to cover/remove your name, email address, and profile photo? For example, what I would do in this case is cover it with a black square, to match the background. Then we can merge the pull request. Thanks!

Will change it tomorrow. Thanks for lettong me know

**Comment by PRMerger12** [comment]
@Aaron-Junker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger3** [comment]
@Aaron-Junker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@Aaron-Junker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@Aaron-Junker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by noraa-junker** [comment]
> Hi @Aaron-Junker - A Microsoft Docs standard is to avoid publishing personal data in images. In **win10-cs-00.png**, in the upper-left corner, could you use an image editing app to cover/remove your name, email address, and profile photo? For example, what I would do in this case is cover it with a black square, to match the background. Then we can merge the pull request. Thanks!

@ktoliver I pixeled it. I hope this is also ok.

**Comment by ktoliver** [comment]
Hi @Aaron-Junker - Thank you for updating the image. Unfortunately, pixelation isn't a prescribed method for obscuring personal data per internal publishing standards. What would make more sense here is to use fictitious information, to preserve the information that's in UI. I've moved the set of commits over to a new pull request in the private repo, and I added a commit to replace the pixelated bits with an approved fictitious name and email address. The PR should be merged shortly. We'll close this pull request.

**Comment by ktoliver** [comment]
(Contributor association with the commits will be retained.)

**Comment by noraa-junker** [comment]
Ok thanks. There's no way for non MSFT employees to use something like a contoso acc to do such screenshots, right?

**Comment by ktoliver** [comment]
> Ok thanks. There's no way for non MSFT employees to use something like a contoso acc to do such screenshots, right?

@Aaron-Junker That's right. An internal website generates fictitious content on request for internal contributors. I don't know of a way for an external contributor to access that information. 👍🏼

**Comment by noraa-junker** [comment]
> > Ok thanks. There's no way for non MSFT employees to use something like a contoso acc to do such screenshots, right?
> 
> @Aaron-Junker That's right. An internal website generates fictitious content on request for internal contributors. I don't know of a way for an external contributor to access that information. 👍🏼 

Thanks for your answer. Too bad but I think I understand why

**Pull request closed without merging**
