### PR TITLE
The image is not formated correctly.

### PR DESCRIPTION
**Pull request by karavar**
The image under section "Select Get to know my handwriting to open the Handwriting Personalization dialog." isn't formatted correctly. Is it because it's inside the note.

### CODE REVIEW

**Comment by mikematteson** [comment]
@karavar : Thanks for your contribution. Going forward, CX asks that Microsoft employees use VSTS to submit documentation changes. Future contributions via GitHub will be closed with a request that you resubmit them via VSTS. More information is at http://aka.ms/windowsauthoring (see **UWP instructions** > **Conceptual content**).

Cc: @Karl-Bridge-Microsoft

**Comment by mikematteson** [comment]
@Karl-Bridge-Microsoft: PR **passed** checklist review. Okay to merge whenever you approve.

**Incidental finding:** Does the other image reference in the same list (just above the one corrected in this PR) have the same problem? Fix it too?

**Comment by karavar** [comment]
Yes please fix the other image too. Thanks!

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for your contributions to the Windows docs! I've found a few other rendering issues with this topic that I will address outside this PR (along with your suggestion).

**Pull request closed without merging**
