### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by mrlacey**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@mrlacey : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Note that publishing in this repository is suspended until Tuesday, May 19. Merging will resume 7:00 AM PT Tuesday. Authors can still review and sign off on PRs during this time. Thanks.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Comment by ktoliver** [comment]
Hi @Karl-Bridge-Microsoft 

PR merges in this repo now need to follow the [Ask Mode process](https://microsoft.sharepoint.com/teams/ContentLearningPMs/_layouts/15/Doc.aspx?sourcedoc={391cae78-5fd4-4cd8-8b2d-70cf1e7b9310}&action=view&wd=target%28Build%202020%2FFAQ.one%7C3a7dc9ca-e520-4fc0-9e3c-96aef35c8da0%2FHow%20do%20I%20submit%20an%20ASK%20MODE%20Request%7C79959a20-6beb-4b97-8fc8-4df7a0277caf%2F%29&wdorigin=703). Otherwise, we'll merge PRs that are signed off beginning at 7 AM on Tuesday, May 19.

**Comment by ktoliver** [comment]
Hi @Karl-Bridge-Microsoft

PR merges in this repo now need to follow the ask mode process. Otherwise, we'll merge PRs that are signed off beginning at 7 AM on Tuesday, May 19. (Repost without link--let me know if you need the information; I can send via email.)

**Pull request merged**
