### PR TITLE
Update channel-types.md

### PR DESCRIPTION
**Pull request by RebPen**
Added note to customers to inform them of a change that limits access to alternate channels on Windows Notification Service (WNS)

### CODE REVIEW

**Comment by PRMerger15** [comment]
@RebPen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by RebPen** [comment]
Just checking on status of this approval....

Thanks,
Rebecca

**Comment by ktoliver** [comment]
@hickeys Have you had a chance to look at the update that's proposed in this pull request?

Thanks.

**Comment by RebPen** [comment]
I still haven't seen this go through, do you have an ETA?

From: Rebecca Penick
Sent: Thursday, June 17, 2021 1:30 PM
To: 'MicrosoftDocs/windows-uwp' ***@***.***>; MicrosoftDocs/windows-uwp ***@***.***>; Kristine Toliver (Aquent LLC) ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/windows-uwp] Update channel-types.md (#3170)

Just checking on status of this approval....

Thanks,
Rebecca

**Comment by ktoliver** [comment]
@hickeys @jwmsft @mijacobs Would one of you be able to review the proposed update?

(I'm not a SME, so I can't provide approval. I PR-review and merge approved pull requests.)

Thanks.

**Comment by ktoliver** [comment]
@RebPen Per the Microsoft Docs contributor guide, "core product team PMs" typically work in the private repo. (I don't know if this applies here.) In the private repo, you can sign off on your own pull requests. Updates made through the public repository need approval of the author or another member of the content team.

**Comment by ktoliver** [comment]
Hi @RebPen - It looks like the content has moved, so the PR can't be merged, even after SME review (it has a file-level merge conflict):

image

I suggest that you close this pull request, and then create a new PR (which will automatically begin with the current file location).

As a PM, you may work in the private repo (-pr). There, you can sign off directly, or you can request review from the content team:

image

Thanks.

**Comment by ktoliver** [comment]
We'll close this PR; it can't be merged in because the updated file has been moved to a different folder since the PR was created. Thanks.

**Pull request closed without merging**
