### PR TITLE
[Registry Preview] Initial drop of registry-preview.md and screenshot

### PR DESCRIPTION
**Pull request by randyrants**
Initial draft of documentation for Registry Preview.

### CODE REVIEW

**Comment by Court72** [comment]
@randyrants 

Thanks for your contribution! A member of the content team will reach out to you.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by randyrants** [comment]
@mattwojo - just FYI, it looks like the feature that is described by this new md file will be art of the 0.69.0 release of the tools, maybe.  No idea if that creates a timeline for this, but wanted to share the info just the same.

**Comment by crutkas** [comment]
Goal is week of April 3rd for 0.69 release.

**Comment by crutkas** [comment]
0.69 is released,

**Review by mattwojo — APPROVED** [review]

**Pull request merged**
