### PR TITLE
Fix url for [Windows SDK - Build 17110]

### PR DESCRIPTION
**Pull request by elbruno**
Fix url for  [Windows SDK - Build 17110]. The correct one is >> https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK

### CODE REVIEW

**Comment by mikematteson** [comment]
@serenaz @elbruno :  Our [PR review criteria](https://review.docs.microsoft.com/en-us/windows-authoring-guide/managing-contributions/editorial-checklist?branch=master#content-quality-criteria) generally require that we *not* hard-code the locale specifier in URLs to sites where browser locale is automatically detected. Does that cause a failure in this case?

**Comment by serenaz** [comment]
The current URL is correct, and yes, @mikematteson, we intentionally left out the locale specifier.

**Comment by elbruno** [comment]
Thanks for the clarification, I fully understand the not hard-code of the locale in url. However, without the locale for [en-us], the download link is not working. Try [https://www.microsoft.com/en-ca/software-download/windowsinsiderpreviewSDK](https://www.microsoft.com/en-ca/software-download/windowsinsiderpreviewSDK) and you'll see.

**Review by serenaz — APPROVED** [review]

**Comment by mikematteson** [comment]
@serenaz : Thanks for merging. Looks like the expected "fallback to English" feature is not enabled or otherwise not working for this URL. Bruno's example was en-ca, and I tried fr-fr and de-de with same 404 result. I'll escalate the fallback failure to our site managers and see whether this is a known issue.

**Comment by elbruno** [comment]
You rock @mikematteson ! 
Thanks

**Comment by mikematteson** [comment]
Thanks @elbruno !
Final word on this (for now) is that there is indeed **no** locale-fallback mechanism for this page. This confirms the need to hard-code the "en-us" locale into this URL.

@serenaz : Looks like the same issue occurs on the [Get started](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/get-started) page (the link appears under "Prerequisites"). If you confirm, would you please add the necessary "en-us" there too via VSTS? Thanks!

**Comment by serenaz** [comment]
Sure thing!

**Pull request merged**
