### PR TITLE
Add v1.60 MDL2 icons

### PR DESCRIPTION
**Pull request by xtoolkit**
hi
i add icons but i don't know official name for this icons.
please add official name or give me official name for this change.
sry 4 my bad english

### CODE REVIEW

**Comment by mijacobs** [comment]
Hello, 
Thanks for your contribution! Can you describe what this update does--were the old icons out of date or incomplete? 
Regards,
Mike

**Comment by xtoolkit** [comment]
@mijacobs hi
segmdl2.ttf version 1.55 in RedStone1 have 1267 icon [range: E700-EF20]
in RS2 138 has been added [range for new icon: EF2C-F1CC]
i add this icons (138) to list. but i don't know name for new icons. can you give me official name for new icons for complete this pull?
thank you

**Comment by xtoolkit** [comment]
@mijacobs hi
i don't know official name for new icons(138). you know?

**Comment by xtoolkit** [comment]
aloooo

**Comment by mijacobs** [comment]
@xtoolkit Thank you for the contributions; this sort of contribution typically comes from our internal teams--I'm working with them to get the  icon names and update the page. I'd love your feedback after I've we've made the update.

**Pull request closed without merging**
