### PR TITLE
[PowerToys]Update DSC samples

### PR DESCRIPTION
**Pull request by jaimecbernardo**
Improve the DSC sample provided in the DSC documentation for PowerToys, according to the changes on https://github.com/microsoft/PowerToys/pull/32494:

- Use the full resource name to improve time for winget to find the resource.
- Make the configure step depend on the install step.
- Use PowerToys package full name for the install step.

### CODE REVIEW

**Comment by jaimecbernardo** [comment]
This one is not dependent on the next release and can go in as soon as approved.
Thank you 😉

**Review by alvinashcraft — APPROVED** [review]
Looks good. Does this need to be held until the PR in the PT repo is merged?

**Comment by jaimecbernardo** [comment]
No need to hold. Although @denelon might ask for some changes in the original PR, so I guess let's hold it to see if it requires extra changes 😉 
Thank you. I'll let you know once that one's approved.

**Comment by denelon** [comment]
I approved the other PR :)

**Pull request merged**
