### PR TITLE
Fix unknown extension error

### PR DESCRIPTION
**Pull request by dongle-the-gadget**

### CODE REVIEW

**Comment by Kellylorenebaker** [comment]
@normesta : PR passes checklist criteria. All yours!

**Comment by dongle-the-gadget** [comment]
Thank you! But I haven’t got the option to merge the pull request.
I need at least 1 approving review is required by reviewers with write access. And my pull request will be automatically be merged.

**Comment by Kellylorenebaker** [comment]
@normesta : Can you take a look at this change and approve and merge as appropriate? It's good from a PRRT review perspective. Thanks!

**Comment by dongle-the-gadget** [comment]
I always try to use the exact same instructions and then I have an error:
I tried to open the App Service of Packaging Project, but client app says:
AppUnavailable: App exists, but not the App Service in the app.

**Comment by dongle-the-gadget** [comment]
Co-creator of the pull requests cannot approve their own pull requests. So I think that reviewers with write access, that means the Microsoft Docs or someone else with a write access with Microsoft Docs to merge. I cannot make an approve and merge my own pull request.

**Comment by normesta** [comment]
Hello - Thank you for the contribution. I'm having the change reviewed by a member of our engineering team to ensure that we are advocating best practice and will reply back as soon as review is complete. Thank you!

**Comment by normesta** [comment]
Hi superkid200. While you might have been able to get this to work by adding extensions directly to the Windows Application Packaging Project, the best practice is to add this extension to the UWP project that references the Windows Runtime Component. 

This topic doesn't adequately explain the mechanics of setting all of that up so I've flagged this topic for a complete refresh so that we can make things a bit clearer. 

In the meantime, I strongly suggest reviewing this topic as it very clearly explains all of the individual steps that you'll need to accomplish to get your app service properly deployed - https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-and-consume-an-app-service . 

Use the Windows Application Packaging project merely as a way to package your desktop application together with any other supportive projects (such as a UWP project that deploys an app service).

I just created a small sample solution that uses the guidance in that app service topic along with the Windows Application Packaging project and all works harmoniously.

**Comment by dongle-the-gadget** [comment]
Sorry, but adding the the UWP project which reference to something is not a best practice, it is a WORST practice. Why? Because if we use UWP package.appxmanifest, the app service cannot contact with the App Service and return unwanted exceptions in StorageFolder.GetFileAsync(string), because I am storing the data in the Packaging project, NOT the UWP app.

**Comment by dongle-the-gadget** [comment]
Here, I will give you what returns:
Packaging project:
Status: Success
Errors about data: None
UWP project:
Status: AppUnavailable
Errors about data: Data cannot be found.

**Comment by dongle-the-gadget** [comment]
Anybody?

**Review by normesta — APPROVED** [review]

**Pull request merged**
