### PR TITLE
Update Schortcut Guide text + image

### PR DESCRIPTION
**Pull request by Jay-o-Way**
Regarding https://github.com/microsoft/PowerToys/issues/13398
> By community request, the use of pressing the Windows key for showing the Shortcut Guide is re-enabled.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger20** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jay-o-Way** [comment]
Version 0.47 has been released. So, ready when you are? 🙂

**Comment by Jak-MS** [comment]
@mattwojo - can you take a look? thanks!

**Comment by mattwojo** [comment]
Awesome! Love this update. Merging. Thanks guys!

**Comment by mattwojo** [comment]
*We've currently got a freeze for some new Windows 11 content going out - but this update should show up early next week.

**Pull request merged**
