### PR TITLE
Fix wrong link

### PR DESCRIPTION
**Pull request by stephtr**
See title 😉

### CODE REVIEW

**Comment by PRMerger10** [comment]
@stephtr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@stephtr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@stephtr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by QuinnRadich — APPROVED** [review]

**Pull request merged**
