### PR TITLE
Initial changes to use-mat.md

### PR DESCRIPTION
**Pull request by techieari**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@arianapadilla : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@Karl-Bridge-Microsoft 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by PRMerger3** [comment]
@arianapadilla : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@arianapadilla : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
