### PR TITLE
Toast notification, badge, and tile updates

### PR DESCRIPTION
**Pull request by andrewleader**
Re-organizing the toast/badge/tile docs menu to be a bit more intuitive and less cluttered.

Before | After
--|--
image | image

Naming has also been updated, changing "Windows apps" to "UWP apps" and "Desktop apps" to "Win32 apps" to be more consistent with current terminology.

And all toast code samples have been updated to use the builder syntax, which is the most preferred way of constructing a toast now.

Before | After
--|--
[Send local toast](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast) | [Send local toast](https://docstaging.z5.web.core.windows.net/aleader/notifications-updates/design/shell/tiles-and-notifications/send-local-toast.html) (Simplified the steps greatly, plus using builder syntax)
[Toast content](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts) | [Toast content](https://docstaging.z5.web.core.windows.net/aleader/notifications-updates/design/shell/tiles-and-notifications/adaptive-interactive-toasts.html?tabs=builder-syntax) (Added tabs for C#/XML and switched to builder syntax)

### CODE REVIEW

**Comment by PRMerger10** [comment]
@andrewleader : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@andrewleader : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @andrewleader -- This pull request was created in the public repo. Per the Docs contributor guide, PMs should work in the private repo, and substantial updates to the content should be made in the private repo. Would you submit the updates in a new PR in the private repo? We'll close this PR. Thanks.

**Comment by andrewleader** [comment]
Hey @ktoliver, I'm aware of that, however the whole purpose of working in the open is to work in the open (when there's no confidential reason to keep info private). Plus other work that I'm working on needs to be public and I need to start that work now rather than wait for it all to be merged to the public repo.

@hickeys this is now ready for review!

**Comment by PRMerger8** [comment]
@andrewleader : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@andrewleader The private repo has automated quality checks and you can view the updates on staging to verify formatting. Plus, you get comprehensive PR review in the private repo to ensure alignment with internal quality standards. But I'll leave it for the repo owner to make the call. Thank you.

**Comment by ktoliver** [comment]
cc @tfosmark @mijacobs @GrantMeStrength

**Comment by andrewleader** [comment]
I've built my own staging site for this exact purpose (since the work to enable staging sites on the public repo hasn't started yet and we need other things we're working on to be publicly previewable via staging so that customers can validate our proposed APIs).

Thus, a preview of this PR can be seen here: https://docstaging.z5.web.core.windows.net/aleader/notifications-updates/design/shell/tiles-and-notifications/send-local-toast.html

**Comment by PRMerger12** [comment]
@andrewleader : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@andrewleader : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@andrewleader : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@andrewleader : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by andrewleader** [comment]
[CI build](https://dev.azure.com/ms-andrewleader/windows-uwp-docs/_build/results?buildId=43&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=24311d03-63ec-5098-c8e5-7df09da2b6d4) of latest commit e29f06a had no warnings within notification documents (warnings are from other people's docs)

```
2020-10-05T19:38:19.2620748Z [2020-10-05 19:38:19.257480Z]: Build completed.
2020-10-05T19:38:19.6853630Z Warning 1 [ hub/package-manager/winget/source.md (line 24) ] : Invalid file link:(~/package-manager/winget/images%5Csource.png).
2020-10-05T19:38:19.6877777Z Warning 2 [ hub/package-manager/winget/show.md (line 21) ] : Invalid file link:(~/package-manager/winget/images%5Cshow.png).
2020-10-05T19:38:19.6941301Z Warning 3 [ hub/package-manager/winget/search.md (line 21) ] : Invalid file link:(~/package-manager/winget/images%5Csearch.png).
2020-10-05T19:38:19.7032238Z Warning 4 [ hub/package-manager/winget/install.md (line 21) ] : Invalid file link:(~/package-manager/winget/images%5Cinstall.png).
2020-10-05T19:38:19.7068509Z Warning 5 [ hub/package-manager/winget/index.md (line 49) ] : Invalid file link:(~/package-manager/winget/images%5Chelp.png).
2020-10-05T19:38:19.7100540Z Warning 6 [ hub/package-manager/winget/index.md (line 46) ] : Invalid file link:(~/package-manager/winget/images%5Cinstall.png).
2020-10-05T19:38:19.7149457Z Warning 7 [ hub/package-manager/package/repository.md (line 34) ] : Invalid file link:(~/package-manager/package/..%5Cwinget%5Cvalidate.md).
2020-10-05T19:38:19.7177301Z Warning 8 [ hub/package-manager/package/repository.md (line 96) ] : Invalid file link:(~/package-manager/package/images%5Cpull-request.png).
2020-10-05T19:38:19.7344923Z Warning 9 [ hub/package-manager/package/repository.md (line 47) ] : Invalid file link:(~/package-manager/package/images%5Cfork.png).
2020-10-05T19:38:19.7376639Z Warning 10 [ hub/apps/winui/winui2/release-notes/winui-2.4.md (line 68) ] : Invalid file link:(~/apps/winui/winui2/release-notes/..%5Cimages%5Ctextbox-darkthemeupdates-after1.gif).
2020-10-05T19:38:19.7503747Z Warning 11 [ hub/apps/winui/winui2/release-notes/winui-2.4.md (line 69) ] : Invalid file link:(~/apps/winui/winui2/release-notes/..%5Cimages%5Ctextbox-darkthemeupdates-after2.gif).
2020-10-05T19:38:19.7679682Z Warning 12 [ hub/apps/winui/winui2/release-notes/winui-2.4.md (line 69) ] : Invalid file link:(~/apps/winui/winui2/release-notes/..%5Cimages%5Ctextbox-darkthemeupdates-before2.gif).
2020-10-05T19:38:19.7710173Z Warning 13 [ hub/apps/winui/winui2/release-notes/winui-2.4.md (line 50) ] : Invalid file link:(~/apps/winui/winui2/release-notes/..%5Cimages%5Ctabview-sizing.gif).
2020-10-05T19:38:19.7735156Z Warning 14 [ hub/apps/winui/winui2/release-notes/winui-2.4.md (line 68) ] : Invalid file link:(~/apps/winui/winui2/release-notes/..%5Cimages%5Ctextbox-darkthemeupdates-before1.gif).
2020-10-05T19:38:19.7766768Z Warning 15 [ hub/apps/winui/winui2/release-notes/winui-2.4.md (line 55) ] : Invalid file link:(~/apps/winui/winui2/release-notes/..%5Cimages%5Ctabview-closebuttononhover.gif).
2020-10-05T19:38:19.7826993Z Warning 16 [ hub/apps/winui/winui2/release-notes/winui-2.4.md (line 83) ] : Invalid file link:(~/apps/winui/winui2/release-notes/..%5Cimages%5CHierarchicalNavView.gif).
2020-10-05T19:38:19.7940425Z Warning 17 [ windows-apps-src/design/controls-and-patterns/index.md (line 88) ] : Invalid file link:(~/design/controls-and-patterns/..%5Cmotion%5Cparallax.md).
2020-10-05T19:38:19.7961563Z Warning 18 [ windows-apps-src/audio-video-camera/play-audio-and-video-with-mediaplayer.md (line 237) ] : Invalid file link:(~/audio-video-camera/uwp/api/windows.media.audio.audiostatemonitor).
2020-10-05T19:38:19.8015706Z Warning 19 [ windows-apps-src/xaml-platform/xaml-overview.md ] : 19 invalid cross reference(s) "<xref:Windows.UI.Xaml.Controls.Page>", "<xref:Windows.UI.Xaml.ResourceDictionary>", "<xref:Windows.UI.Xaml.Window.Content%2A?displayProperty=nameWithType>", "<xref:Windows.UI.Xaml.FrameworkElement.Name%2A>", "<xref:Windows.UI.Xaml.Media.Animation.ObjectAnimationUsingKeyFrames>", "<xref:Windows.UI.Xaml.Controls.CheckBox>", "<xref:Windows.UI.Xaml.Style>", "<xref:Windows.UI.Xaml.FrameworkElement.Style%2A?displayProperty=nameWithType>", "<xref:Windows.UI.Xaml.Controls.Border>", "<xref:Windows.UI.Xaml.Style?displayProperty=nameWithType>", "<xref:Windows.UI.Xaml.Controls.Button>", "<xref:Windows.UI.Xaml.Controls.Primitives.ButtonBase.Click>", "<xref:Windows.UI.Xaml.FrameworkElement.Language%2A?displayProperty=nameWithType>", "<xref:Windows.UI.Xaml.Media.SolidColorBrush>", "<xref:Windows.UI.Xaml.Application.Resources%2A>", "<xref:Windows.UI.Xaml.ResourceDictionary.MergedDictionaries%2A>", "<xref:Windows.UI.Xaml.DebugSettings.IsOverdrawHeatMapEnabled?displayProperty=nameWithType>", "<xref:Windows.UI.Xaml.Controls.ListView>", "<xref:Windows.UI.Xaml.Controls.GridView>".
2020-10-05T19:38:19.8140331Z Warning 20 [ windows-apps-src/cpp-and-winrt-apis/move-to-winrt-from-cx.md (line 37) ] : Invalid link: '<a href="cpp-and-winrt-apis/interop-winrt-cx.md#taking-a-cwinrt-project-and-adding-cx-support">Taking a C++/WinRT project and adding C++/CX support</a>'. The file cpp-and-winrt-apis/interop-winrt-cx.md doesn't contain a bookmark named 'taking-a-cwinrt-project-and-adding-cx-support'.
2020-10-05T19:38:19.8192503Z Warning 21 [ windows-apps-src/cpp-and-winrt-apis/move-to-winrt-from-cx.md (line 62) ] : Invalid link: '<a href="cpp-and-winrt-apis/interop-winrt-cx.md#taking-a-cwinrt-project-and-adding-cx-support">Taking a C++/WinRT project and adding C++/CX support</a>'. The file cpp-and-winrt-apis/interop-winrt-cx.md doesn't contain a bookmark named 'taking-a-cwinrt-project-and-adding-cx-support'.
2020-10-05T19:38:19.8231121Z Warning 22 [ windows-apps-src/devices-sensors/pos-device-support.md (line 120) ] : Invalid link: '<a href="devices-sensors/point-of-service.md#out-of-band-pairing">out of band pairing</a>'. The file devices-sensors/point-of-service.md doesn't contain a bookmark named 'out-of-band-pairing'.
2020-10-05T19:38:19.8261761Z Build succeeded with warning:
2020-10-05T19:38:19.8280304Z     22 Warning(s)
2020-10-05T19:38:19.8298067Z     0 Error(s)
```

**Review by hickeys — APPROVED** [review]
@andrewleader These changes look great. Thank you for taking the time!

**Comment by PRMerger16** [comment]
@hickeys : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by andrewleader** [comment]
Thanks Shawn!!

**Pull request merged**
