### PR TITLE
Update system-backdrop-controller.md

### PR DESCRIPTION
**Pull request by ghost1372**

### CODE REVIEW

**Comment by Court72** [comment]
@jwmsft

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Jay-o-Way** [comment]
That's confusing: the doc says "xaml backdrop" but the actual code is C#. Where's the xaml part?
```xaml
<Window x:Class="MyApp.MainWindow">

    <Window.SystemBackdrop>
        <MicaBackdrop MicaKind="BaseAlt"/>
    </Window.SystemBackdrop>

</Window>
```
https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.micabackdrop?view=windows-app-sdk-1.3

**Comment by ghost1372** [comment]
This doc is based on version 1.3 release notes
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-13

In version 1.3 we cant use system backdrop in xaml side if you do this you will face with compile error.
I didnt test it with 1.3.1

**Comment by Jay-o-Way** [comment]
It should be working with 1.3 already, but there might be another dependency, somewhere. Not my area of expertise. But anyways, why not incluse the XAML code for a XAML app/window?

**Comment by jwmsft** [comment]
@ghost1372, thanks for this update. You are correct that the XAML wasn't working in the 1.3.0 release; I can confirm that it does work in the 1.3.1 release. However, this PR will conflict with an update to all the SystemBackdrop related docs that is currently in review and should be published shortly, so I am closing this PR.

**Pull request closed without merging**
