### PR TITLE
Update lists.md

### PR DESCRIPTION
**Pull request by ChaosEx**
Fix broken link based on issue #2864

### CODE REVIEW

**Comment by PRMerger16** [comment]
@TeeVenDick : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Verified the fix; changed to a relative link and removed the locale per Microsoft style. Thanks @TeeVenDick

**Comment by Jay-o-Way** [comment]
Hey, why did _he_ get all the thanks? 😆

**Comment by jwmsft** [comment]
Thank you for reporting the break, @Jay-o-Way !!!

**Comment by Jay-o-Way** [comment]
Haha, you're welcome. Have a great weekend!

**Pull request merged**
