### PR TITLE
Update MainPage.xaml.cs

### PR DESCRIPTION
**Pull request by Shivam7-1**
issue #4454 
Earlier Code: Currently, the code includes a `SignOutButton_Click `event handler, but it doesn't perform the sign-out functionality. 
After Modification: Implemented the sign-out functionality in the code, you can modify the `SignOutButton_Click` event handler

### CODE REVIEW

**Comment by Shivam7-1** [comment]
@microsoft-github-policy-service agree

**Comment by American-Dipper** [comment]
@mattwojo - I see you have modified this file. Can you review the proposed changes?  

 
IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.  

 

#label:"aq-pr-triaged" 

@MicrosoftDocs/public-repo-pr-review-team

**Comment by Shivam7-1** [comment]
@American-Dipper Can any one review this PR please

**Comment by Shivam7-1** [comment]
@PRMerger-2 Can any one review this PR please

**Review by alvinashcraft — APPROVED** [review]
This looks good, but I'm going to make a note that this entire sample should be updated to remove the use of RoamingSettings. They're no longer supported in Windows 11: https://learn.microsoft.com/uwp/api/windows.storage.applicationdata.roamingsettings?view=winrt-22621#remarks

**Pull request merged**
