### PR TITLE
Update PowerToys docs with Push to talk 

### PR DESCRIPTION
**Pull request by pajawojciech**
related to [PR #24892](https://github.com/microsoft/PowerToys/pull/24892)

### CODE REVIEW

**Comment by Court72** [comment]
@mattwojo

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by stefansjfw** [comment]
@pajawojciech Your screenshot has strings in Polish (I believe). To be consistent with docs let's keep it in English. You can take the screenshot from my PR

**Review by stefansjfw — CHANGES_REQUESTED** [review]
@mattwojo Please do not merge this until screenshot is updated

**Comment by crutkas** [comment]
0.69 is released,

**Comment by mattwojo** [comment]
This appears to be a duplicate of https://github.com/MicrosoftDocs/windows-dev-docs/pull/4360

**Pull request closed without merging**
