### PR TITLE
Updating docs from PT issue 13940

### PR DESCRIPTION
**Pull request by crutkas**
From issue https://github.com/microsoft/PowerToys/issues/13940

### CODE REVIEW

**Comment by PRMerger12** [comment]
@crutkas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jay-o-Way** [comment]
shortcut-guide.md should be changed too

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger15** [comment]
@crutkas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by crutkas** [comment]
> shortcut-guide.md should be changed too

done

**Review by mattwojo — APPROVED** [review]

**Pull request merged**
