### PR TITLE
[PowerToys] Keyboard Manager lists key mappings that may not be usable on certain keyboards

### PR DESCRIPTION
**Pull request by dedavis6797**
Addresses [PowerToys 12711](https://github.com/microsoft/PowerToys/issues/12711)

cc: @mattwojo

### CODE REVIEW

**Comment by PRMerger18** [comment]
@dedavis6797 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by crutkas** [comment]
What is pending here?  @mattwojo

**Comment by mattwojo** [comment]
Looks good to me. Auto-assign is broken on this repo currently so just didn't see it earlier.

**Pull request merged**
