### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by asklar**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@asklar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by adrastogi — APPROVED** [review]
Looks good! Thanks for the improvements. :)

**Comment by mattwojo** [comment]
Thanks for the contribution @asklar! Would love to hear if you have any feedback on what else you would like to see included in this performance content as we continue to create new docs if you have another spare moment. ♥️

**Pull request merged**
