### PR TITLE
Specify VS2022

### PR DESCRIPTION
**Pull request by angelazhangmsft**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@angelazhangmsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by zaryaf — APPROVED** [review]

**Comment by zaryaf** [comment]
LGTM. Can be merged into docs.

**Comment by ktoliver** [comment]
@Court72

**Pull request merged**
