### PR TITLE
Update system-resource-allocation.md

### PR DESCRIPTION
**Pull request by walbourn**
Needs some updates for UWP on Xbox Series X|S

### CODE REVIEW

**Comment by PRMerger12** [comment]
@walbourn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@walbourn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"

**Comment by walbourn** [comment]
I'm going to restart this PR as I have some related changes as well as to resolve conflicts

**Pull request closed without merging**
