### PR TITLE
PowerToys v0.31 updates

### PR DESCRIPTION
**Pull request by dedavis6797**
Updating PowerToys content for the v0.31 release.

Main highlights:
- New Editor UI for FancyZones
- Adding back Boost Library info and new usage example for PowerRename
- New system settings commands and two plugins to specify reg keys and Windows services for PowerToys run.

@mattwojo please review as well.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@dedavis6797 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by enricogior** [comment]
@dedavis6797 
we also need to update the Space around zones section, this is from my PR, feel free to take the picture and rephrase the text
https://github.com/enricogior/windows-uwp/blob/fz-update-0.31/hub/powertoys/fancyzones.md#space-around-zones

**Comment by enricogior** [comment]
@dedavis6797 
we also need to update the text for
https://github.com/dedavis6797/windows-uwp/blob/docs/hub/powertoys/fancyzones.md#choose-your-layout-layout-editor
since it still says `Selecting apply sets that layout to the monitor.` but we don't have the `Apply` button anymore.

Same for `The chosen monitor will then be the target of the selected layout when applied.` the `when applied` part can be removed.

**Comment by ktoliver** [comment]
Hi @dedavis6797 - This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. We can keep this PR open for review and merge, but would you make future content updates in the private repo? Thank you!

**Comment by mattwojo** [comment]
Hi @ktoliver - This particular content set doesn't follow that guidance for developing in the private repo as it relates to an open-source product that is developed largely by the user community. I'll follow up off-line about it. 
Thanks! ~Matt

**Comment by PRMerger7** [comment]
@dedavis6797 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dedavis6797** [comment]
I believe that last commit takes care of all the updates from our team.

@mattwojo feel free to do a final review and help us get this checked in.

**Comment by PRMerger16** [comment]
@mattwojo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by mattwojo — APPROVED** [review]

**Pull request merged**
