### PR TITLE
Tweaked wording of WebVR section

### PR DESCRIPTION
**Pull request by leweaver**
to more clearly state that the feature only works within Microsoft Edge, not UWP applications.

### CODE REVIEW

**Comment by mikematteson** [comment]
@leweaver : Thanks for your contribution! Going forward, CX asks that Microsoft employees use VSTS to submit documentation changes. More information is at http://aka.ms/windowsauthoring (see **UWP instructions** > **Conceptual content**).

Cc: @QuinnRadich

**Comment by mikematteson** [comment]
@QuinnRadich   PR **passed** review checklist. Please evaluate the proposed changes further. Thanks!

**Comment by QuinnRadich** [comment]
Ooops - this PR never got closed. Issue was discussed and handled on the internal side.

**Comment by leweaver** [comment]
Thanks!

**Pull request closed without merging**
