### PR TITLE
Update microsoft-store-services-sdk.md

### PR DESCRIPTION
**Pull request by LanceMcCarthy**
Updated Step 6 in the NuGet package installation directions section. Until you restart Visual Studio, you will not see the Extension SDK in the list.

### CODE REVIEW

**Comment by mcleanbyron** [comment]
Thank you for your contribution. I and several other people have tested the current instructions several times and the existing steps work fine for us (that is, we can add the "Microsoft Advertising SDK for XAML" assembly reference after simply closing and reopening the project; we don't need to close and restart Visual Studio at step 6). 

I am following up with the engineering team who owns this SDK to confirm the correct instructions, but can you please try the existing steps again with just closing and reopening the project to confirm that this doesn't work for you?

**Comment by LanceMcCarthy** [comment]
I unloaded and reloaded the UWP Project and didn't see either Extension SDK (Advertising or Services) under 'Add Reference > Universal Windows > Extensions'.

When you say "closing and reopening" do you mean the solution? 

If yes, then we only need to update the docs to say "Close and reopen the Solution' instead of "project"

**Comment by LanceMcCarthy** [comment]
Okay, I just did a "File > New" test and confirmed the following:

- Closing and re-opening the UWP _project_ **does not** update the Extension SDKs list
- Closing and re-opening the _Solution_ **does** update the Extension SDKs list

I can change my PR to say "Close and reopen the solution" instead of "Restart Visual Studio"

**Review by mcleanbyron — APPROVED** [review]
Thanks for your contribution, and good call on clarifying that it is the solution that needs to be closed and reopened rather than the project. I am merging your pull request, with a few minor edits.

**Pull request merged**
