### PR TITLE
Powertoys Run ValueGenerator docs

### PR DESCRIPTION
**Pull request by IHorvalds**
This PR is in reference to https://github.com/microsoft/PowerToys/pull/26097.

### CODE REVIEW

**Review by alvinashcraft — APPROVED** [review]
Looks good. Approving to publish with the 0.72.0 release.

**Comment by IHorvalds** [comment]
Thank you! :)

**Comment by IHorvalds** [comment]
@alvinashcraft Hey, it seems I made a mistake in the formatting in this section:
https://learn.microsoft.com/en-us/windows/powertoys/run#value-generator-plugin

image

**Comment by alvinashcraft** [comment]
@IHorvalds  Good catch. I can go try to fix it up quickly.

**Comment by IHorvalds** [comment]
It looks right in the GitHub preview:
https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/run.md
image

**Comment by alvinashcraft** [comment]
It looks fine in my VS Code preview pane too. I'm going to try adding a line break after "Examples:" and push to my branch. I can preview on the internal docs site with the windows-dev-docs-pr repo.

**Comment by alvinashcraft** [comment]
It looks good on the review site in my branch after adding some line breaks. I'll get a PR merged ASAP.

**Comment by IHorvalds** [comment]
That's awesome! Thank you!

**Comment by alvinashcraft** [comment]
You're welcome. The table should be rendering on the live site now. 😊

**Pull request merged**
