### PR TITLE
Update declare-background-tasks-in-the-application-manifest.md

### PR DESCRIPTION
**Pull request by aruproy14**
Fix typos in SupportsMultipleInstances sample

### CODE REVIEW

**Comment by PRMerger18** [comment]
@aruproy14 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
#label:"aq-pr-triaged"

**Comment by aruproy14** [comment]
@ShannonLeavitt @GrantMeStrength This PR has been open for a month. Can you please review and submit?

**Comment by Court72** [comment]
@GrantMeStrength 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

**Pull request merged**
