### PR TITLE
Add File Locksmith

### PR DESCRIPTION
**Pull request by ivanstosic-janea**
This PR adds some docs for the upcoming new PowerToy.

### CODE REVIEW

**Review by jaimecbernardo — APPROVED** [review]
LGTM! Thank you!

**Comment by jaimecbernardo** [comment]
@crutkas , Please take a look.

**Comment by crutkas** [comment]
LGTM.  @mattwojo fyi

**Comment by crutkas** [comment]
@mattwojo please wait for us to ship PowerToys next week. @cinnamon-msft please loop matt in when we go live

**Comment by jaimecbernardo** [comment]
Hi @mattwojo , PowerToys has been released: https://github.com/microsoft/PowerToys/releases/tag/v0.64.0
Can you please merge this PR?

**Review by mattwojo — APPROVED** [review]
Looks good! Merging. :)

**Pull request merged**
