### PR TITLE
Improve samples

### PR DESCRIPTION
**Pull request by eNeRGy164**
- Don't use smart quotes in code samples (makes copy&paste easier for readers)
- Textual placeholders between <> were not rendered, escaped characters

### CODE REVIEW

**Comment by PRMerger6** [comment]
@eNeRGy164 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@jwmsft - can you review? thanks.

edited to add: if you want us to move this into the private repo so we can see these changes with validation, proofing, and staging tools, let us know.

**Review by jwmsft — APPROVED** [review]

**Comment by jwmsft** [comment]
#sign-off

**Comment by jwmsft** [comment]
@eNeRGy164 , thanks for submitting these fixes!

**Pull request merged**
