### PR TITLE
linker invalid

### PR DESCRIPTION
**Pull request by Jeaninezjq**
The document [Bluetooth Low Energy](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/bluetooth-low-energy-overview#feedback) has several invalid links.

### CODE REVIEW

**Comment by garycentric** [comment]
@eliotcowley  : The PR **passed** the acceptance checklist. Please evaluate further and approve/complete the PR if appropriate. Thanks!

**Comment by PRMerger12** [comment]
@Jeaninezjq : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by eliotcowley — APPROVED** [review]

**Comment by PRMerger8** [comment]
@eliotcowley : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by eliotcowley** [comment]
Thanks @Jeaninezjq, I've merged your changes and they should be live soon.

**Pull request merged**
