### PR TITLE
Docs: Update host custom control with xaml islands doc 

### PR DESCRIPTION
**Pull request by freistli**
for a custom control loading failure issue with WinUI library control

### CODE REVIEW

**Comment by PRMerger20** [comment]
@freistli : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by marb2000 — APPROVED** [review]
Unfortunately, it's a common workaround.

**Comment by PRMerger20** [comment]
@mcleanbyron : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by mcleanbyron — APPROVED** [review]

**Comment by PRMerger12** [comment]
@mcleanbyron : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@mcleanbyron : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
