### PR TITLE
Powertoys - FancyZones - update 0.31

### PR DESCRIPTION
**Pull request by enricogior**
Changes to the Powertoys FancyZones page to reflect the new FancyZones Editor UI in the 0.31 release.
New images and minor changes to the descriptions.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@enricogior : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by enricogior** [comment]
@dedavis6797 
I didn't realize you already made some updates for FancyZones.
Feel free to review this PR in case there is anything that is useful for your PR, or close it if you already covered all the basics.
Thanks.

**Comment by dedavis6797** [comment]
Thanks @enricogior, I just incorporated your FancyZones updates to the PR I made. I don't have permissions to close this PR, so feel free to close it when you get a chance.

**Comment by enricogior** [comment]
@dedavis6797 
done. Thanks.

**Pull request closed without merging**
