### PR TITLE
[PowerToys] Run: Update calculator section and add service plugin

### PR DESCRIPTION
**Pull request by htcfreek**
Update docs for new behavior introduced in microsoft/PowerToys/pull/18159.

image

Add information for service plugin about the new search features introduced in microsoft/PowerToys/pull/17985.
- Update plugin keyword table examples.
- Add section for services plugin.

image

**Please don't merge before an approval of @crutkas or @jaimecbernardo and the release of PT v0.59.0 in June 2022!!**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@htcfreek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@htcfreek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@mattwojo, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. Thanks.

#label:"aq-pr-triaged"

**Comment by htcfreek** [comment]
@mattwojo 
The feature changes coming wiith th release v0.60.0 at the end of June. Please hold this PR until the end of June.

**Comment by PRMerger10** [comment]
@htcfreek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger3** [comment]
@htcfreek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by htcfreek** [comment]
@crutkas , @jaimecbernardo
I have updated the PR and added the changes for service plugin too.

**Review by jaimecbernardo — APPROVED** [review]
LGTM! Thank you for the contribution!

**Comment by Court72** [comment]
@mattwojo 

Could you review this proposed update to your article and enter `#sign-off` in a comment if it's approved for merge?

Thanks!

**Comment by Court72** [comment]
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger14** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Comment by htcfreek** [comment]
We can merge this

**Comment by htcfreek** [comment]
@mattwojo 
Can you please review this?

**Comment by PRMerger18** [comment]
@mattwojo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattwojo** [comment]
Made some minor wording adjustments. Looks good to me. Merging.

**Comment by htcfreek** [comment]
> Made some minor wording adjustments. Looks good to me. Merging.

Thank you. Great adjustments.

**Pull request merged**
