### PR TITLE
Small PowerToys changes

### PR DESCRIPTION
**Pull request by Jay-o-Way**
- Updated installation info (dependencies)
- A typo here & there
- A bit of https://github.com/MicrosoftDocs/windows-uwp/issues/3822
- A shot at https://github.com/MicrosoftDocs/windows-uwp/issues/3672

Should be an open-and-shut case :)

### CODE REVIEW

**Comment by PRMerger9** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger-2** [comment]
@Jay-o-Way : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AnnaMHuff** [comment]
@mattwojo  - Can you review the proposed changes? 

*IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. All changes will be reviewed for typos or other language errors prior to merge.

Thanks!

#label:"aq-pr-triaged"

**Comment by Jay-o-Way** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@Jay-o-Way: I'm sorry - only the author of this article, @mattwojo, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by mattwojo** [comment]
#sign-off

**Comment by PRMerger-2** [comment]
@mattwojo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by mattwojo — APPROVED** [review]

**Pull request merged**
