### PR TITLE
Add Base64 Decoding to PowerToys Run

### PR DESCRIPTION
**Pull request by LeagueOfPoro**
- Add Base64 Decoding to PowerToys Run

### CODE REVIEW

**Review by alvinashcraft — APPROVED** [review]
This looks good to me. Let me know when the functionality is available, and we can move ahead with this docs PR. Thanks!

**Comment by Jay-o-Way** [comment]
JSYK @htcfreek

**Comment by LeagueOfPoro** [comment]
> This looks good to me. Let me know when the functionality is available, and we can move ahead with this docs PR. Thanks!

The PR was merged to PowerToys - https://github.com/microsoft/PowerToys/pull/27835

**Comment by alvinashcraft** [comment]
Thanks. After the release is out, I'll merge this.

**Pull request merged**
