### PR TITLE
typo: notfication -> notification

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by VernonMSFT** [comment]
@mijacobs The PR **passed** the acceptance checklist. Please evaluate further and approve/complete the PR if appropriate. Thanks!

**Review by mijacobs — APPROVED** [review]

**Review by mijacobs — CHANGES_REQUESTED** [review]
We just switched our toc files to a yaml based toc, so we have a merge conflict. Can you get the latest master later today and make your changes in the toc.yml file?

**Comment by nschonni** [comment]
I'll try rebasing when I'm home

**Comment by nschonni** [comment]
@mijacobs rebased for the YAML change

**Review by mijacobs — APPROVED** [review]

**Pull request merged**
