### PR TITLE
Reclaim "Hello World" for other search results

### PR DESCRIPTION
**Pull request by colin-home**
Remove "Hello World" from title, because it's confusing people who land here searching for a K&R/Stroustrup-style command-line app in C++. They are probably looking for https://docs.microsoft.com/en-us/cpp/build/vscpp-step-1-create instead.

### CODE REVIEW

**Comment by mikematteson** [comment]
@GrantMeStrength @QuinnRadich : PR **passed** review checklist. Please evaluate the proposed changes further. Note that if title changes, corresponding TOC must be changed accordingly too.

**Comment by colin-home** [comment]
Sorry, I didn't notice the TOC issues until later. And I see that the C++ topic is parallel with a similarly-named C# topic at the same level. Perhaps both topics should be updated to have explicit UWP mentions in the titles.

**Comment by QuinnRadich** [comment]
It's a good suggestion, but as you've noted it requires more than just changes to this one file.

No approval on this PR, but I'll go ahead and make some changes on our end. Thanks.

**Comment by colin-home** [comment]
Closing per comment by @QuinnRadich for more comprehensive fix.

**Pull request closed without merging**
