### PR TITLE
Removed duplicate paragraph.

### PR DESCRIPTION
**Pull request by debalin**

### CODE REVIEW

**Review by TylerMSFT — CHANGES_REQUESTED** [review]
Hi Debalin,
Thank you for your interest in our docs. I would rather this paragraph not be removed because it explains what a device family is.

**Comment by TylerMSFT** [comment]
It’s been assigned to me twice and I already responded to it.

**Comment by debalin** [comment]
Hey @TylerMSFT I was not suggesting to remove that paragraph completely. If I'm not wrong, the exact same paragraph appears in two places under the heading of "Device Families". 

devicefamilies

Was that intentional? I thought that might be a overlook and hence submitted the pull request suggesting to remove the second duplicate one. Hope that helps.

**Review by TylerMSFT — APPROVED** [review]
I see - thank you for catching that!

**Comment by debalin** [comment]
No problem, happy to help. 👍

**Pull request merged**
