### PR TITLE
Check MD docs against reference / Authoring Pack (part 1)

### PR DESCRIPTION
**Pull request by Jay-o-Way**
Issue: #3837
Many files, but (kinda) small changes!

### CODE REVIEW

**Comment by Court72** [comment]
@Jay-o-Way 

Ignore my previous comment! I see that you're not an FTE.

**Comment by Court72** [comment]
@mijacobs
@GrantMeStrength 
@jillre 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by Jay-o-Way** [comment]
> Thanks for submitting these updates!

You're welcome. Hope it's all good that I do this. Got a few Q's in my issue, hoping for some guiding on those soon :)
And now I see I got conflicts to solve too... Gosh, what did I start on, lol. \#sigh

**Comment by Jay-o-Way** [comment]
I really gotta do things differently...

**Pull request closed without merging**
