### PR TITLE
porting installation and requirements from readme.md

### PR DESCRIPTION
**Pull request by Karl-WE**
there is a known issue listed on the readme.md of winget that is not listed on the docs
https://github.com/microsoft/winget-cli/edit/master/README.md

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Karl-WE : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Karl-WE** [comment]
PR #3042 is obsolete if you choose to merge this one.

**Comment by PRMerger19** [comment]
@mattwojo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattwojo** [comment]
Thanks for contributing this @Karl-WE. I'm closing it out as it looks we took too long to approve and the install steps have already been updated now. My apologies! I hope that you continue to contribute PRs and file issues on anything you see that needs an update. I'm finally getting up to speed on the Package Manager content and should be able to turn things around a bit more quickly for the docs.

**Comment by Karl-WE** [comment]
Thanks @mattwojo so long ago even reading my changes doesn't help to remind me the original idea for this PR.
Certainly it would end in a merge conflict.
As you said, hope future PR would be triaged and signoff more timely.

Thanks for your housekeeping effort.

**Comment by mattwojo** [comment]
Yes, big mea culpa on this one.
We get so much feedback and this got buried during some transition of who was keeping track of what.
Thanks for your understanding Karl.

**Pull request closed without merging**
