### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by AsaoluElijah**
Changed **by selecting Ctrl+C** to **by clicking Ctrl+C** since this is a keyboard action and not a selectable element on the GUI

### CODE REVIEW

**Comment by PRMerger13** [comment]
@AsaoluElijah : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by bartlannoeye** [comment]
@AsaoluElijah clicking makes it sound like a mouse interaction?

**Comment by AsaoluElijah** [comment]
Yeah 🤦, maybe **typing** is the right word?
Should I submit a pr for that and close this? :nerd_face:

**Comment by ktoliver** [comment]
@mattwojo Would you review this PR? Thanks.

FYI, guidance in the [Microsoft Writing Style Guide - Describing interactions with the UI](https://docs.microsoft.com/style-guide/procedures-instructions/describing-interactions-with-ui) is to use *select* for keys and keyboard shortcuts (in the table under **Select**).

**Comment by mattwojo** [comment]
Thanks for contributing to the docs by raising this issue @AsaoluElijah. Our content guide folks have identified the term 'selecting' as the preferred interaction word for keyboard shortcuts, so I'm going to close this PR. I appreciate the challenge though as we're consistently reassessing whether we're using the best terminology to communicate understanding. I think in this particular case, the fact that the instructions call out that this action is in the CLI, I'm going to stand by the term 'select'. Please keep contributing and letting us know if you see anything in the docs that you think could be better. ~Matt

**Pull request closed without merging**
