### PR TITLE
small nits

### PR DESCRIPTION
**Pull request by Jay-o-Way**
just text improv

### CODE REVIEW

**Comment by niels9001** [comment]
> **uri to WinUI Gallery is pending**, because `winui3gallery:/item/Icons` doesn't open a specific page in the app. Maybe @niels9001 knows?

Yes, this is a known issue since moving from the WinUI 2 to the WinUI 3 Gallery. Opened an issue to track it: [#1300](https://github.com/microsoft/WinUI-Gallery/issues/1300)

**Comment by Court72** [comment]
Trying a close/reopen to clear the validation warnings.

**Comment by Court72** [comment]
Looks good; thanks @jay-o-way

**Comment by Jay-o-Way** [comment]
Wooh, that was quick!
I wish everything would be address in such a way 🙃

Off topic: you guys should totally think about using `![INCLUDE]` for this bit.

**Comment by Jay-o-Way** [comment]
p.s. i wouldn't say this looks good


😐

**Comment by Court72** [comment]
@jay-o-way

I agree! Feel free to open a PR to submit a formatting fix.

**Pull request merged**
