### PR TITLE
Added code snippets for new Backdrop APIs in system-backdrop-controller.md

### PR DESCRIPTION
**Pull request by CosmicPredator**
- Added sample code for the new XAML Backdrop APIs.
- Addressed the old Backdrop Setting Code example with WindowsAppSDK version `1.2.x` and the new API's with `1.3.x`.
- Added new XAML Backdrop Code example for setting `MicaAlt` as the system backdrop.

### CODE REVIEW

**Comment by CosmicPredator** [comment]
@microsoft-github-policy-service agree

**Comment by Court72** [comment]
@jwmsft

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Anglemmj7** [comment]
@microsoft-github-policy-service terminate

**Comment by CosmicPredator** [comment]
@jwmsft What about the Pull Request? Any changes needed?

**Comment by jwmsft** [comment]
@CosmicPredator, thanks for submitting this update, and sorry for the delay in reviewing it. It looks like this change is essentially the same as an update made right about the same time that you created this PR, which will cause a conflict with the current doc. If you would like to suggest further improvements to the updated doc in its current form, we'd welcome an updated PR. Thanks

**Comment by CosmicPredator** [comment]
@jwmsft Thanks for notifying me. It seems like the required changes are already made in the docs. So there is no need for my PR to get merged. I'll close my PR now.
A Kind request, try to be as fast a possible next time.🤗

**Pull request closed without merging**
