### PR TITLE
Add missing dashes

### PR DESCRIPTION
**Pull request by markaldridge**
Several commands are missing the second dash.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@markaldridge : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Looks good; verified. @markaldridge - Would you take a moment to sign the Microsoft Contributor Licensing Agreement (CLA)? Then, we can merge the PR.

Admin note: PR added to Bug https://github.com/MicrosoftDocs/windows-uwp/pull/2481 for CLA verification issue.

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks @markaldridge

**Pull request merged**
