### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by asklar**
update Facebook -> Meta

### CODE REVIEW

**Comment by PRMerger16** [comment]
@asklar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@QuinnRadich 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by Jay-o-Way** [comment]
#3433 is also still open. (Why is that?)

**Comment by asklar** [comment]
superseded by #3954 as more stuff needs to be updated and this PR is now out of date

**Pull request closed without merging**
