### PR TITLE
Update screen-ruler.md default activation shortcut

### PR DESCRIPTION
**Pull request by nx-frost**
Update default activation shortcut to `⊞ Win`-`Ctrl`-`Shift`-`M` to resolve conflict with Windows Explorer built-in shortcut (microsoft/powertoys#32623)

### CODE REVIEW

**Review by alvinashcraft — APPROVED** [review]
Thanks, This update looks good. I will hold this PR until the shortcut update is released in PowerToys.

**Comment by nx-frost** [comment]
@alvinashcraft I deleted my fork of this repo after the change was merged into PowerToys 0.82, however I am noticing this documentation was not merged. Do I need to re-create the PR, or can it be pulled as-is? Thanks.

**Comment by alvinashcraft** [comment]
Hi @nx-frost. Let me see what I can do with this PR.

**Comment by alvinashcraft** [comment]
I'm not seeing a simple way to use the existing PR or commit to merge this change. I could create a PR myself, but I'd rather have you get credit for the change in the git history. Do you want to submit another PR for this, @nx-frost.

**Comment by nx-frost** [comment]
I have opened #5064.

**Pull request closed without merging**
