### PR TITLE
Delete device-portal-ssl.md

### PR DESCRIPTION
**Pull request by Anglemmj7**
(default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

### CODE REVIEW

**Comment by Anglemmj7** [comment]
(default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

**Comment by Court72** [comment]
@Anglemmj7 

Thank you for your contribution. Would you take a moment to sign the [Contributor License Agreement (CLA)](https://github.com/MicrosoftDocs/windows-dev-docs/pull/4423#issuecomment-1556043030)? Note that you should enter the highlighted comment for the first option:
image

After the CLA is signed, someone can review your pull request. Thanks!

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Anglemmj7** [comment]
microsoft-github-policy-service agree

**Comment by Anglemmj7** [comment]
> @Anglemmj7 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

(default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
@microsoft-github-policy-service agree

**Comment by Court72** [comment]
@Karl-Bridge-Microsoft

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

**Comment by Karl-Bridge-Microsoft** [comment]
PR rejected. 

Cannot accept random file deletions.

**Pull request closed without merging**
