### PR TITLE
UWP in Mixed Reality Tutorial

### PR DESCRIPTION
**Pull request by seesharprun**
I was browsing both the UWP documentation (<https://docs.microsoft.com/en-us/windows/uwp/index>) and Mixed Reality documentation (<https://developer.microsoft.com/en-us/windows/mixed-reality/development>) and I noticed that a tutorial does not exist that takes you from not knowing anything about Windows Mixed Reality to running a simple app using an immersive headset.

I created a simple tutorial that walks someone through creating a subset of the Unity **roll-a-ball tutorial** and runs it as an immersive reality UWP application. 

In this PR I created a few things:

- A link on the UWP index page (<https://docs.microsoft.com/en-us/windows/uwp/index>) to a ``mixed-reality`` section

- A ``mixed-reality`` landing page with a brief description and a link to a ``getting-started`` tutorial.

- A ``getting-started`` tutorial that walks someone through creating the Unity app, modifying the Player Settings and running the app in the **Mixed Reality Portal**.

Here's the justification: There are bits and pieces of documentation out there already, but none of it is compehensive. For example, I found this:

- In the Azure Mobile Engagement documentation, there are is a Unity UWP tutorial that is out-of-date: (<https://docs.microsoft.com/en-us/azure/mobile-engagement/mobile-engagement-unity-roll-a-ball>).

- The actual Unity **roll-a-ball** tutorial has out-of-date videos in some parts: (<https://unity3d.com/learn/tutorials/projects/roll-ball-tutorial>).

- The overview documentation on the Mixed Reality side makes a lot of assumptions about the reader's knowledge about Unity: (<https://developer.microsoft.com/en-us/windows/mixed-reality/unity_development_overview>, <https://developer.microsoft.com/en-us/windows/mixed-reality/using_visual_studio>).

The goal with this PR is to create a comprehensive tutorial that a developer can follow on Day 1 when they open their mixed reality headset box. I  hope this is useful to the community.

### CODE REVIEW

**Comment by stfnilsson** [comment]
Thanks!

**Comment by QuinnRadich** [comment]
Thank you for your contribution.

Immersive apps such as these aren't something that we cover in the windows-uwp repo, and we don't have any current plans to change that. That being said, I've reached out to the Mixed Reality team to notify them of this PR.

**Comment by seesharprun** [comment]
Thanks. I reviewed their documentation and didn’t see a repo so I thought this was the “closest” documentation repo.

Thanks for notifying their team.

**Comment by QuinnRadich** [comment]
Alright. I've heard back from the Mixed Reality folks.

Though it shouldn't live in this repo, and while currently the Mixed Reality dev center doesn't take external contributions, we don't want to discourage devs from helping over devs. Take a look at the Academy courses that already exist for similar purposes: https://developer.microsoft.com/en-us/windows/mixed-reality/academy . If you think that your tutorial addresses gaps in that content, please post it in the Mixed Reality developer forums (https://forums.hololens.com/categories/building-holographic-apps ) so that other devs can benefit from your work.

Thank you!

**Comment by seesharprun** [comment]
This is perfect! Thanks

Sidney Andrews
sidney@seesharprun.net
@sidney_andrews
________________________________

**Pull request closed without merging**
