### PR TITLE
Update show-multiple-views.md

### PR DESCRIPTION
**Pull request by marb2000**
Adding VisualTreeHelper.FindElementsInHostCoordinates  to the table and the way of using it on XAML Islands

### CODE REVIEW

**Comment by PRMerger15** [comment]
@marb2000 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @marb2000 - PMs should work in the private repository, per the contributor guide. We'll keep this PR for review in the public repo, but would you create future PRs in the private repo? Thanks!

**Review by jwmsft — APPROVED** [review]

**Comment by jwmsft** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
