### PR TITLE
Update ratings-and-reviews.md

### PR DESCRIPTION
**Pull request by IpsitaChoudhary**
Updating documentation as lifetime rating count feature is being made live in Store on 08/04

### CODE REVIEW

**Comment by PRMerger8** [comment]
@IpsitaChoudhary : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by alvinashcraft — APPROVED** [review]

**Comment by alvinashcraft** [comment]
@Jak-MS This one was not ready to merge until 8am PDT on Thursday. Can you revert this?

**Comment by Jak-MS** [comment]
@alvinashcraft - i've reverted the changes... you'll need to open a new PR with the changes.   Please don't approve or sign off until the changes are ready to merge. Thanks!

tagging: @IpsitaChoudhary @hickeys

**Comment by alvinashcraft** [comment]
Thanks, @Jak-MS. I'll create a new PR now. I thought that leaving the Do Not Merge tag on it would keep it safe. I'll hold off on doing a code review next time.

**Comment by Jak-MS** [comment]
@alvinashcraft - I also recommend using the private repo for anything time critical. the public repos are only monitored by the pr review team 2x daily and not on the weekends. thanks.

**Comment by Jak-MS** [comment]
you can also put the PR in draft mode if you'd like to review and approve it but not have it merged.

**Comment by alvinashcraft** [comment]
Thanks, @Jak-MS. I created a new PR (2868) in the private repo. It'll be merged at 8am PDT on 08/04.

FYI - @hickeys and @IpsitaChoudhary

**Pull request merged**
