### PR TITLE
Updating Registering your app and receiving the credentials for your cloud service section of WNS documentation

### PR DESCRIPTION
**Pull request by mariahhart**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@mariahhart : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
Hi @mariahhart 

Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules.

After you review staging and fix all validation issues, you can add the sign-off comment to let PR reviewers know that the updates are ready to be merged.

For more information, see [Should I work in a private or a public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master)?

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/fork-and-clone?branch=master).

Would you create a pull request in the private repo to make these updates? We'll close this PR. Let us know if you need help moving the commits in this PR. 

Thank you.

**Comment by mariahhart** [comment]
I'm not aware of where to find "the private repo."

**Comment by ShannonLeavitt** [comment]
Hi Mariah,

As far as we know, the private version of your repo is windows-uwp-pr. The -pr at the end indicates that it’s private rather than public.

Hope that helps.

Shannon

**Pull request closed without merging**
