### PR TITLE
line 40 should be norm(V-Lp) ?

### PR DESCRIPTION
**Pull request by JToUnknown**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@ShawnMeiUstc : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by stevewhims** [comment]
Thank you! Let me get a technical review and then I'll go ahead and complete this.

Thanks!
Steve

**Review by clandrew — APPROVED** [review]

**Comment by clandrew** [comment]
For anyone else who might have needed it like I did the URL for this is [https://docs.microsoft.com/en-us/windows/uwp/graphics-concepts/camera-space-transformations](https://docs.microsoft.com/en-us/windows/uwp/graphics-concepts/camera-space-transformations)

**Comment by stevewhims** [comment]
Thanks for the PR and reviews!

-Steve

**Pull request merged**
