### PR TITLE
Remove Tag option

### PR DESCRIPTION
**Pull request by markaldridge**
The tag option is not listed as one of the options within the install help of winget so I assume this was added by mistake.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@markaldridge : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
It appears per https://github.com/MicrosoftDocs/windows-uwp/pull/2481 that the CLA needs to be signed before the PR can be reviewed. @markaldridge Thanks.

**Comment by ktoliver** [comment]
@KevinLaMS - Could you review the proposed update to your article? Thanks.

**Review by KevinLaMS — APPROVED** [review]

**Comment by KevinLaMS** [comment]
Thanks for catching it.

**Pull request merged**
