### PR TITLE
Update capture-device-controls-for-video-capture.md

### PR DESCRIPTION
**Pull request by strongstrongyiwen**
Added notes to indicate user need to stop streaming before setting value to video hdr control.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@strongstrongyiwen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by drewbatgit** [comment]
#sign-off

**Review by kasumman — APPROVED** [review]

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
