### PR TITLE
Missing a using directive

### PR DESCRIPTION
**Pull request by avaryx**
`ListViewBase` and `ContainerContentChangingEventArgs` require `Microsoft.UI.Xaml.Controls`.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@avaryx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]

**Comment by PRMerger5** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by avaryx** [comment]
@stevewhims to give you some more context to this request I had found that when I was working through the project (and saving along the way) that this specific reference was removed. I believe this is most likely due to Code Cleanup that is built into Visual Studio. When reviewing the Code Cleanup configuration, I see the default profile calls out **Remove unnecessary Imports or usings**. Other developers may not face the same interruption that I did here, but I felt it didn't hurt to call it out specifically. You may have a more graceful way to go about this.

Thanks for the article! I haven't delved into Visual Studio for Windows apps in a while and wanted to get more familiar with WinUI 3, and this was very straight-forward and engaging. I appreciate it!

**Comment by stevewhims** [comment]
Thanks, @avaryx!

**Pull request merged**
