### PR TITLE
Adding note for P/Invoke for .NET apps

### PR DESCRIPTION
**Pull request by duncanmacmichael**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@duncanmacmichael : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@duncanmacmichael : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@duncanmacmichael : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by v-andreaco** [comment]
@duncanmacmichael 

This pull request was opened in the public repo. Internal contributors should [work in the private repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master), per the Microsoft Docs contributor guide. 

It looks like you have created pull requests in the private repo before. Would you make this content update in the private repo so that validation and Acrolinx can run,?

Thank you! We'll close this PR.

**Comment by duncanmacmichael** [comment]
@v-andreaco Oh, I see. When I was on the docs team we were encouraging everyone, including feature PMs, to just use the public edit button, but it looks like the guidance has changed. 

I'm having trouble getting to the private repo; I know my account is properly linked to MS, has 2FA, and is part of the MicrosoftDocs org. It could be that I don't have the proper URL; I've tried all the steps on the linked page above but it could be that I don't know what the name of the private repo is. I don't want to discuss it publicly though - can you either email me internally what the name of the private repo is so I can access/clone it, or simply un-close this public PR and merge it? I can guarantee you that the links are fine and don't contain "en-us". ;-)

**Pull request closed without merging**
