### PR TITLE
[PowerToys] Update VCM docs - push-to-talk feature

### PR DESCRIPTION
**Pull request by stefansjfw**
For the upcoming PowerToys release v0.69.0, new Push-To-Talk (and Push-To-Reverse) feature will be introduced in Video Conference Mute module

ref PR https://github.com/microsoft/PowerToys/pull/24892

### CODE REVIEW

**Comment by stefansjfw** [comment]
@crutkas Please take a look

**Comment by ShannonLeavitt** [comment]
@mattwojo 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by pajawojciech** [comment]
@stefansjfw [here](https://github.com/MicrosoftDocs/windows-dev-docs/blob/a15006898a560e8ced936cde001b1330ead7db8d/hub/images/pt-video-conference-mute-settings.png) is my proposition of screenshot

**Comment by crutkas** [comment]
good to go after we release .69

**Comment by crutkas** [comment]
0.69 is relased,

**Review by mattwojo — APPROVED** [review]

**Pull request merged**
