### PR TITLE
Code-blocking time zones list

### PR DESCRIPTION
**Pull request by yoichinak**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@yoichinak : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by hickeys** [comment]
@yoichinak 

Thanks for taking the time to submit this PR. Can you explain a little more about what the utility of converting the time zone list from a table into a code block would be? Perhaps there's a workflow that we didn't think of when we created this table.

Thanks,
Shawn

**Comment by yoichinak** [comment]
Thank you for your attention.
Before my PR, the time zone list looked like a simple text. To improve readability with small changes, I tried code-bolocking.
Now, it was table-made by https://github.com/MicrosoftDocs/windows-uwp/commit/072505ffb33c56c7de29d331164a67f1788b0b0c#diff-81e511069c8d9359b8e97402c5313dc5 . That is the best solution :)

**Comment by hickeys** [comment]
Thanks @yoichinak. By the time I looked at it, it was already a table. Sounds like a code block would have been an upgrade from no formatting at all, and it's on me for waiting two months to review your PR. Thanks for your contribution, and I'll try to look at it more quickly next time :)

**Pull request closed without merging**
