### PR TITLE
Update PowerToys KBM screenshots

### PR DESCRIPTION
**Pull request by dillydylann**
https://github.com/microsoft/PowerToys/pull/28473

### CODE REVIEW

**Review by alvinashcraft — APPROVED** [review]
Looks great. We can merge this when the release goes out.

**Comment by Jay-o-Way** [comment]
@alvinashcraft

**Comment by alvinashcraft** [comment]
Thanks @Jay-o-Way. So, this is going into the next release? The last time I checked with the team, it wasn't released yet.

Do you want to take the PR out of draft, @dillydylann?

**Comment by Jay-o-Way** [comment]
@alvinashcraft the updated UI is already release with v0.76.x so yes please :)

**Comment by alvinashcraft** [comment]
@niels9001 @Jay-o-Way - It looks like the screenshots were already updated in another PR by @stefansjfw. https://github.com/MicrosoftDocs/windows-dev-docs/pull/4761

Recommend we close this one. Sorry it got missed when 0.76.0 went out.

**Comment by Jay-o-Way** [comment]
Perfect!

**Comment by alvinashcraft** [comment]
Closing as screenshots were updated in another PR. Thanks for your contribution!

**Pull request closed without merging**
