### PR TITLE
multiple files: fix typos

### PR DESCRIPTION
**Pull request by schneiderl**
Please be aware that this pull request was automatically created using [gtf](https://github.com/schneiderl/gtf) - a typo fixing bot

You should be able to merge this with no other problems.
In case the proposed changes do not make sense, I would be glad to hear about it.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@schneiderl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @schneiderl 

Because PR reviewers directly merge PRs that fix typos and basic formatting issues, I'll give you some feedback on your tool. The PR introduces some errors that should be fixed or removed from the pull request:

- Multiple instances of incorrectly replacing "layed" with "laid" in "displayed" (several files)

   image

- Replaced "wether" with "weather," when it should be "whether" (windows-apps-src/audio-video-camera/camera-profiles.md)

  image

- Changed "seeked" to "sought" in an object called **BreaksSeekedOver**. I probably wouldn't change that because it matches the terminology.

   image

I've checked all other fixes and they are straightforward spelling fixes that are OK to merge.

Thanks. #hold-off

cc repo business approvers @mijacobs @GrantMeStrength 

@tfosmark

**Comment by schneiderl** [comment]
@ktoliver Thanks a lot for your feedback. I've already changed the tool so that it doesn't repeat those mistakes.
I'm not currently at my computer but I'll fix this PR taking into consideration the points you've mentioned.
After that, I'll notify everybody involved in this PR so we can think of merging this.

**Review by stevewhims — APPROVED** [review]
Thanks for this, some great fixes here.

**Comment by stevewhims** [comment]
Apologies, I merged after scanning the changes, but I didn't notice the issues that @ktoliver did. So I've reverted the changes. Please create a fresh PR with the corrected changes. Sorry for that! -Steve

**Comment by schneiderl** [comment]
@stevewhims I'll manually do this tomorrow morning. Once again thank you for pointing out that issues @ktoliver.

**Comment by stevewhims** [comment]
Thanks, @schneiderl! Feel free to add me as a reviewer.

**Pull request merged**
