### PR TITLE
Update acrylic.md

### PR DESCRIPTION
**Pull request by c16u**
Improved writing conventions (e.g. capitalized proper nouns and replaced transparency with translucency for linguistic accuracy).

### CODE REVIEW

**Comment by Kellylorenebaker** [comment]
@mijacobs : PR passes checklist review.

**Comment by mijacobs** [comment]
@c16u , thank you for your contribution! We don't treat "acrylic" as a proper noun in our other articles. I'm talking to the team about deciding on a consistent approach.

**Comment by Sleeplikelion** [comment]
zz

**Review by mijacobs — CHANGES_REQUESTED** [review]
We use lowercase "acrylic" in the rest of our docs. We're considering treating the word as a proper noun, but for now we need to be consistent with our other articles.

**Comment by c16u** [comment]
Are you able to make the changes? @mijacobs

**Review by c16u — COMMENTED** [review]
<hr>

**Comment by c16u** [comment]
@mjacobs Done.

**Review by mijacobs — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
