### PR TITLE
Update NavigationView documentation to be up to date with SDK version 16232

### PR DESCRIPTION
**Pull request by VojtechStep**
Fix the Text property being removed from the NavigationViewItem class with alternate solution for passing navigation metadata in the latest Windows SDK

### CODE REVIEW

**Comment by mikematteson** [comment]
Closing/reopen to recheck CLA status.

**Comment by VojtechStep** [comment]
@mikematteson I didn't sign the CLA because, as I stated in the response e-mail, my name was incorrectly formatted in the form: `Vojtěch Štěpanč&#237;k` instead of `Vojtěch Štěpančík`. As soon as the form is fixed, I'll be happy to sign the agreement.

**Comment by mikematteson** [comment]
@VojtechStep Thanks for that information. We're looking into the form issue now.

**Comment by VojtechStep** [comment]
@mikematteson Any progress on that? I haven't received any new e-mail nor has the form been updated.

**Comment by mikematteson** [comment]
@VojtechStep I apologize for this late response to your last comment. It looks like two things have happened since you wrote:

- **An update to the license system has evidently been deployed.** I don't know the details about what bugs were fixed, though. Would you mind trying again to sign? (I don't *think* I need to close and reopen the PR like I did before, but will certainly try that if you can't get back to the form.) I'm hopeful that this will work for you now, but your feedback on it will be helpful either way.
- **It looks like independent changes to the code examples in this documentation have been received from our internal teams, and incorporated.** This may have changed or eliminated the context on which your submission was based. If you have further comments or corrections on the updated examples, we'd love to have them.

Again, I'm sorry for the time this has all taken. Many thanks for engaging and contributing your ideas,

CC: @jwmsft

**Comment by jwmsft** [comment]
Sorry the CLA signing didn't work. This article has been updated for the final SDK release, so this pull request is now out of date.

**Pull request closed without merging**
