### PR TITLE
Fixing naming guidelines

### PR DESCRIPTION
**Pull request by noraa-junker**
This PR fixes the naming to match the styling guide and trademark rights.

* Replaced `and newer` with `and later`
* Replaced `Windows 10/11` with `Windows 10 or Windows 11`

### CODE REVIEW

**Comment by PRMerger19** [comment]
@Aaron-Junker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@Aaron-Junker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by noraa-junker** [comment]
@Karl-Bridge-Microsoft thanks for merging!

**Pull request merged**
