### PR TITLE
if Time and space are fixed variables.

### PR DESCRIPTION
**Pull request by Bcabisca1**
Time and space are fixed measurements therefore it can be calculated the objects in a photo and their relative size proportional to scale of other objects to provide relative manipulation of digital images in real time simulations or for mixed reality viewing used for object insertions in virtual environments. Some of us are still windows lovers. Linux sometimes doesn't play nice in sandbox. This information will be valuable in proving real-time data image collection for legal issues. Time stamps and metadata can be used if not altered, can digital images be used in court without metatags?

### CODE REVIEW

**Comment by PRMerger5** [comment]
@jwmsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AnnaMHuff** [comment]
@mijacobs  - Can you review the proposed changes?

*IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

Thanks!

#label:"aq-pr-triaged"

**Comment by mijacobs** [comment]
I don't work on this content, adding @John Kennedy Direct ***@***.***>, the team that does.

**Comment by GrantMeStrength** [comment]
Thanks for the feedback. I think these changes have already been made: I see no references to RS5 in the docs.
Thank you for taking the time to file this feedback.
-John

**Pull request closed without merging**
