### PR TITLE
Update host-standard-control-with-xaml-islands-cpp.md

### PR DESCRIPTION
**Pull request by asklar**
Try to clarify the actual implementation of `maxversiontested`

### CODE REVIEW

**Comment by PRMerger18** [comment]
@asklar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by asklar** [comment]
@DHowett @ChrisGuzak @GovM-MSFT  fyi

**Review by mcleanbyron — APPROVED** [review]

**Comment by PRMerger10** [comment]
@mcleanbyron : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@mcleanbyron : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by mcleanbyron — APPROVED** [review]

**Pull request merged**
