### PR TITLE
[Peek] Update docs to reflect new navigation keys

### PR DESCRIPTION
**Pull request by daniel-odrinski**
Related to issue: https://github.com/microsoft/PowerToys/issues/26592

### CODE REVIEW

**Comment by Court72** [comment]
@mattwojo

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by mattwojo** [comment]
Thanks for the update @DanWiseProgramming!

**Comment by Jay-o-Way** [comment]
Errr, you mised one space.

**Comment by daniel-odrinski** [comment]
Right, well-spotted @Jay-o-Way . Thanks for fixing!

**Pull request merged**
