### PR TITLE
Add link to ThemeShadow class

### PR DESCRIPTION
**Pull request by mrlacey**
For #2287

### CODE REVIEW

**Comment by PRMerger20** [comment]
@mrlacey : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by jwmsft — APPROVED** [review]

**Comment by PRMerger13** [comment]
@jwmsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jwmsft** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
