### PR TITLE
And a tool to get the InstallerType of a installer

### PR DESCRIPTION
**Pull request by Reset816**
There's no document to tell us how to identify InstallerType. And sometimes it's hard for us to distinguish the type between inno and exe. This tool can help.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@Reset12138 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Reset12138 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@Reset12138 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KevinLaMS** [comment]
@Reset12138  This would a great issue on the client CLI repo.  Would you be willing to post there? https://www.github.com/microsoft/winget-cli

**Comment by mcleanbyron** [comment]
Based on the response from @KevinLaMS, I am closing this pull request for now. If you still feel that these changes should be made to the docs, please reopen with more information.

**Pull request closed without merging**
