### PR TITLE
Correct lowLevelDevices versus lowLevel capability

### PR DESCRIPTION
**Pull request by jordanrh1**
Correct and clarify information regarding the lowLevelDevices capability, and the lowLevel device capability. Two very different things with similar and misleading names!

### CODE REVIEW

**Review by ooeygui — COMMENTED** [review]
Looks good

**Comment by mikematteson** [comment]
@msatranjr @jordanrh1 :
*PR review against the [PR checklist](https://review.docs.microsoft.com/en-us/windows-authoring-guide/managing-contributions/editorial-checklist?branch=master) is complete, with the following findings.

- **Blocking issue:** [RESOLVED]
  ✅  Requirement: *Links to pages that do not require a locale code to render must be coded as locale-agnostic (that is, they must not contain "/en-us" in the URL).* **Please remove "/en-us" term from docs.microsoft.com URLs in the PR text.**

- **Non-blocking issue:**
  ⚠️ : Requirement: *Links to pages that do not require a locale code to render must be coded as locale-agnostic (that is, they must not contain "/en-us" in the URL).* **Please remove "/en-us" term from docs.microsoft.com URLs in this topic that are outside the PR scope. This fix is not required for PR acceptance, but will contribute to overall content quality.**

**Comment by jordanrh1** [comment]
Removed en-us from new links.

**Comment by jordanrh1** [comment]
@msatranjr @mikematteson I have removed en-us from the links. Please review when you get a chance. Thanks.

**Comment by mikematteson** [comment]
@jordanrh1 : Sorry for the delay in getting back to this. I see the 'en-us/' has been removed from the **device interface** link URL, but there are 5 or 6 other URLs later in the PR text that still include the locale specifier. Would you please remove those too? 

@msatranjr : Would you please review the PR further and let Jordan know if additional changes will be needed beyond what I've flagged from the checklist? Thanks!

**Comment by jordanrh1** [comment]
@mikematteson Oops. I went ahead and removed the other en-us references.

**Comment by mikematteson** [comment]
@jordanrh1 : Confirmed that locale specifiers have been removed from the PR text, so this submission now **passes** our acceptance checklist. Still need Michael to review.

@msatranjr :  Please review. Also, please note:
- The GitHub UI is reporting a merge conflict for this PR now. Would you please resolve if possible?
- Some 'en-us' locale specifiers remain in URLs outside the scope of the PR. Please address in the private repo as time permits.

**Comment by jordanrh1** [comment]
Fixed merge conflict.

**Comment by jordanrh1** [comment]
@mikematteson Any other changes you'd like me to make?

**Comment by mikematteson** [comment]
@jordanrh1 Looks good, thanks. I've marked all checklist hits as resolved.
@msatranjr Merge conflict and locale specifiers have been addressed. Any other concerns to work out with Jordan, or can this be merged? Thanks!

**Pull request merged**
