### PR TITLE
[PowerToys] Add Peek docs

### PR DESCRIPTION
**Pull request by SeraphimaZykova**
For the upcoming PowerToys release v0.70.0, a new Peek module feature will be introduced in PowerToys.

ref PR: https://github.com/microsoft/PowerToys/pull/25922

### CODE REVIEW

**Comment by jaimecbernardo** [comment]
@crutkas, for visibility

**Comment by Court72** [comment]
@SeraphimaZykova 

Thanks for your contribution. A member of the content team will review it.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by crutkas** [comment]
Looks good to me.  We go live at 8am 5/23 Pacific

**Comment by jaimecbernardo** [comment]
Hi @mattwojo , This can go in. 0.70.0 is release already. Thank you!

**Comment by jaimecbernardo** [comment]
Nevermind. I see it's already live :)

**Comment by mattwojo** [comment]
Yes, I pulled it into our private Build release branch. I'll close this PR.

**Pull request closed without merging**
