### PR TITLE
Update PowerShell to install in Sandbox

### PR DESCRIPTION
**Pull request by glawrence**
The current script does not work, there is a typo and missing dependency as well as being an older version. I have fixed these, tested with Windows 10 and 11 but tried to keep the script simple and like the original.

### CODE REVIEW

**Comment by glawrence** [comment]
@KevinLaMS appreciate you are probably busy, but please could you let me know if there is a process I should follow to get this reviewed, or if I have missed something. Thanks

**Comment by VShrubowich** [comment]
@glawrence, thank you for this. I came up with a different solution using the Microsoft Store URI for Microsoft.UI.Xaml.2.7, but found the `Invoke-WebRequest` inconsistently resulted in an "Access Denied" error.  Your solution works much better.

The only thing I would change is to either make the dot-sourcing of the files consistent, which would keep it simpler, or, since these commands may be put into a script residing on a read-only mapped folder inside the Windows Sandbox, put the downloaded files into the user temporary folder.  This would change the commands to:
```powershell
$ProgressPreference='SilentlyContinue'
Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.4.10173/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile "$($Env:TEMP)\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"
Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile "$($Env:TEMP)\Microsoft.VCLibs.x64.14.00.Desktop.appx"
Invoke-WebRequest -Uri https://www.nuget.org/api/v2/package/Microsoft.UI.Xaml/2.7.3 -OutFile "$($Env:TEMP)\Microsoft.UI.Xaml.2.7.3.zip"
Expand-Archive -Path "$($Env:TEMP)\Microsoft.UI.Xaml.2.7.3.zip" -DestinationPath "$($Env:TEMP)\Microsoft.UI.Xaml.2.7.3" -Force
Add-AppxPackage "$($Env:TEMP)\Microsoft.VCLibs.x64.14.00.Desktop.appx"
Add-AppxPackage "$($Env:TEMP)\Microsoft.UI.Xaml.2.7.3\tools\AppX\x64\Release\Microsoft.UI.Xaml.2.7.appx"
Add-AppxPackage "$($Env:TEMP)\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"
```
I also found that I could install the latest version of winget automatically by changing the URI for it to 'https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle', but any future changes in dependencies in newer versions would require the article to be updated again.

**Comment by glawrence** [comment]
Thanks @VShrubowich I will take that onboard but do some testing first, so I am certain the script works

**Comment by mattwojo** [comment]
Thank you for this contribution @glawrence. Apologies for the delay. This issue was fixed in https://github.com/MicrosoftDocs/windows-dev-docs/commit/ca90ce0471458f85af6dc789200b263affcfd8ec

**Comment by PDeets** [comment]
@mattwojo It looks like the commit you refer to does not address the issue of the missing dependency on Microsoft.UI.Xaml. It only fixes the missing period in the filename. I think the fix from this PR is still needed.

**Comment by mattwojo** [comment]
Oh! Thanks @PDeets. I'll reopen.

**Comment by glawrence** [comment]
I have taken on board your suggestion @VShrubowich 

@mattwojo and @PDeets I believe this is all good to go, but happy to be corrected on that

**Comment by ShannonLeavitt** [comment]
@mattwojo @PDeets @KevinLaMS - Could you review this PR?

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by glawrence** [comment]
Sorry @ShannonLeavitt @mattwojo @PDeets and @KevinLaMS I think this PR has a dodgy commit from me as well as a validation warning, so I have rerolled it with #4332 so I will close this, but hopefully we can now switch to my new one

**Pull request closed without merging**
