### PR TITLE
Update title bar page to reflect changes of Windows App SDK 1.3.1

### PR DESCRIPTION
**Pull request by Mysterious-Dev**
All is in the title ^^.

https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-131-13230502000

For EOL, when I try to edit this file with Github Editor, I have this warning :
image

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@jwmsft 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Mysterious-Dev** [comment]
@jwmsft Well, I updated the date of page ^^

**Comment by Mysterious-Dev** [comment]
Any news for this PR ?

**Review by jwmsft — APPROVED** [review]

**Comment by jwmsft** [comment]
> Any news for this PR ?

Thanks for the PR, and sorry for the delay. Catching up after Build and holidays.

**Pull request merged**
