### PR TITLE
Create Private-Audience-documentation.md

### PR DESCRIPTION
**Pull request by marmuc680**
don't merge this, the file is work in progress

### CODE REVIEW

**Comment by ktoliver** [comment]
This appears to be a duplicate of #2603. We'll close this PR.

**Comment by marmuc680** [comment]
Hi Kristine,

I am a vendor.
________________________________

**Comment by marmuc680** [comment]
Hi Kristine,
I am working with PFX team and we're adding a new file  here and it's still a WIP- waiting for Shawn to upload some screenshots

**Comment by PRMerger19** [comment]
@marmuc680 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request closed without merging**
