### PR TITLE
Mention a new third-party winget repository

### PR DESCRIPTION
**Pull request by mherrmann**
This PR adds mention of a new third-party winget repository provider.

The provider is my company, [Omaha Consulting GmbH](https://omaha-consulting.com) under the web site [winget.pro](https://winget.pro). We've been helping companies auto-update their Windows applications since 2016. Our contributions to this space have focused on [Omaha](https://github.com/google/omaha) until now. This is Google's technology for auto-updates in Chrome.

Some references to hopefully convince you that our service is an honest offering in the space, and not ill-intentioned or spam:

 * [My pull requests in google/omaha](https://github.com/google/omaha/pulls?q=is%3Apr+author%3Amherrmann). Omaha is deployed on the roughly 1 billion Windows machines that have Chrome and Edge installed. That Google merged my PRs into their code base can (I hope) be seen as a sign of trust.
 * [Public acknowledgement by Brendan Eich](https://twitter.com/BrendanEich/status/1338552498018156544), the inventor of JavaScript, that his company Brave works with us.
 * [My GitHub profile](https://github.com/mherrmann) shows that 7.5k+ people have starred my open source projects.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@mherrmann : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by mherrmann** [comment]
Hi @KevinLaMS have you had a chance to look at this PR? If there's something you need from me to get it merged, please just let me know :-)

**Comment by mherrmann** [comment]
Sorry to bother you again @KevinLaMS. Could you take a look at this PR?

**Comment by ktoliver** [comment]
@mcleanbyron Would you be able to review the proposed change? 

Thanks.

**Comment by mherrmann** [comment]
@ktoliver is there someone else we could ask? Looking at the public contribution graph, it appears that @mcleanbyron may be working on other things.

**Comment by mherrmann** [comment]
@GrantMeStrength @mijacobs could you take a look at this PR please?

**Comment by denelon** [comment]
@mherrmann We are investigating the best way to fairly represent third-party offerings related to the Windows Package Manager. We've seen a few OSS tools and are now aware of the winget.pro offering. I believe we may remove the section related to third-party repositories all together. We can then evaluate the options for best helping our customers become aware of third-party offerings.

**Comment by mherrmann** [comment]
@denelon I see. Can you merge this PR until then? I don't think it's unfair to anyone at this point and when the section gets removed then it won't be a problem either.

**Comment by mattwojo** [comment]
Thanks for submitting this contribution @mherrmann. I've actually just removed the third-party repo offerings section from the Windows Package Manager docs. It's not quite the right place to list those offerings as we try to keep these docs focused on providing technical guidance.
I did, however, just file a pull request to add a third-party repo offerings page to the winget-pkg repo (which is also linked to in the Windows Package Manager docs): https://github.com/microsoft/winget-pkgs/pull/45836
I included your company's offering in the PR.. please feel welcome to update if you'd like anything changed in the description. I basically just copy-pasted what you wrote in this PR though. 
Thanks again and apologies for the delay as we sorted out how to handle this.

**Comment by mherrmann** [comment]
Makes sense. Thank you @mattwojo!

**Pull request closed without merging**
