### PR TITLE
More lifetime fixes

### PR DESCRIPTION
**Pull request by oldnewthing**
Missed some spots in the previous update #3724. Sorry.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@oldnewthing : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"

**Comment by drewbatgit** [comment]
#sign-off

**Comment by QuinnRadich** [comment]
Ran into weird merge complaints here (and unsurprisingly git is not thrilled with me pushing merge conflict fixes over to your fork) so I'm resolving this over here: https://github.com/MicrosoftDocs/windows-dev-docs/pull/4116

**Pull request closed without merging**
