### PR TITLE
[PowerToys] Update policy docs for 0.83.0 release (Changes from ADMX/ADML refactoring.)

### PR DESCRIPTION
**Pull request by htcfreek**
This PR updates the documentation for the Group Policy for PowerToys. The changes will be part of the v0.83.0 release.

---

**PLEASE DO NOT MERGE BEFORE:**
- A review from the PowerToys core maintainers.
- The release of PowerToys `v0.83.0`.
- The merge of the PR: microsoft/PowerToys/pull/33529

### CODE REVIEW

**Review by alvinashcraft — APPROVED** [review]
Looks good. Thanks! We'll hang onto this until it's time for 0.83.0.

**Review by alvinashcraft — APPROVED** [review]

**Comment by htcfreek** [comment]
No auto merge yet. It is for the next release and not the pne from yesterday

**Comment by alvinashcraft** [comment]
> No auto merge yet. It is for the next release and not the pne from yesterday

Yep. This one is on my list for 0.83.0. Thanks!

**Comment by htcfreek** [comment]
@alvinashcraft 
The feature PR is merged. Should I mark the PR as ready yet, because I am out of office when the release happens? Or can you do this too?

**Comment by alvinashcraft** [comment]
@htcfreek Thanks for the heads-up. I can mark it ready for review when the release is out. It's probably best to keep it in draft to make sure nobody else acts on it early. I've got this one on my radar for the next release.

**Pull request merged**
