### PR TITLE
Update WinUI 3 tutorials for C++

### PR DESCRIPTION
**Pull request by sotanakamura**
C# sample code is converted to C++. Some explanation are added for supporting C++ development.

### Bug
In last section "Bind the GridView to the Images collection", it throws an exception about access violation. Binding RatingControl Value property to `ImageFileInfo::ImageRating` has problem. Please review the code and check it.

### CODE REVIEW

**Comment by sotanakamura** [comment]
@microsoft-github-policy-service agree

**Comment by Court72** [comment]
@stevewhims

Can you review the proposed changes? Note that the changes are extensive and will need to be moved into the private repo for staging and automated checks. Let us know if you'd like help doing that.

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by stevewhims** [comment]
Hi, @sotanakamura, and thank you so much for this PR! :)

I've made a start applying the changes here over into my own pull-request. Because there are a lot of changes I'd like to make, so doing the transfer like that (rather than editing this PR) is going to be a better workflow for me.

I don't know how long it'll take me to finish my PR. I need to switch over to some higher priority work, but I'll come back to this soon. In the meantime, so that it's not accidentally merged, I'll close this PR. But I'll continue to work from the changes in the Files tab.

Thanks again! :)
-Steve

**Comment by stevewhims** [comment]
Thanks again! The topic is now updated, and live: [Tutorial: Create a simple photo viewer with WinUI 3](https://learn.microsoft.com/windows/apps/get-started/simple-photo-viewer-winui3). Binding the rating seems to work ok now.

-Steve

**Comment by sotanakamura** [comment]
Thank you for reviewing and merging my PR. I tested updated C++/WinRT sample code, but I still have the same bug on binding RatingControl after binding as `ItemsSource="{x:Bind Images}`  in Step 13. Please check it.

**Comment by sotanakamura** [comment]
The updated sample code is missing const reference. I created PR #4365.

**Comment by stevewhims** [comment]
> Thank you for reviewing and merging my PR. I tested updated C++/WinRT sample code, but I still have the same bug on binding RatingControl after binding as `ItemsSource="{x:Bind Images}` in Step 13. Please check it.

Thanks, @sotanakamura. Yes, it seems like that last step doesn't work for the C++ case, so I've marked it in the topic as C#-only. I can work around the issue by changing the implementation of the rating property, but that seems like a step too far. Let's just leave it like this, and I'll revisit it in future if/when the platform changes.

**Pull request closed without merging**
