### PR TITLE
Close code block

### LINKED ISSUE #1785: Code block not closed
Hi team, this is a reference to https://github.com/MicrosoftDocs/windows-uwp.ja-jp/issues/31. Some paragraphs are not getting localized because there's missing closure for a code block in the file hub/apps/desktop/modernize/using-the-visual-layer-with-windows-forms.md.

The Code Block missing the closure is this one:
  
```csharp
    public CompositionHost()
    {
        InitializeComponent();

        // Get the window handle.
        hwndHost = Handle;

        // Create dispatcher queue.
        dispatcherQueue = InitializeCoreDispatcher();

        // Build Composition tree of content.
        InitComposition(hwndHost);
    }
```

Thanks!

### PR DESCRIPTION
**Pull request by bartlannoeye**
Fixes #1785

### CODE REVIEW

**Comment by PRMerger9** [comment]
@bartlannoeye : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
Apparently this was already fixed in another PR. Thanks.

**Comment by bartlannoeye** [comment]
@jborsecnik please re-evaluate this PR, I see the fix done in another PR (like you mentioned) not applied yet.

**Comment by jborsecnik** [comment]
It seems this needs to be re-opened.

**Comment by jborsecnik** [comment]
Sorry, I think I confused this with another PR. Merging now. Thanks for the head's up!

**Pull request merged**
