### PR TITLE
Fixed Extension XML element typo

### PR DESCRIPTION
**Pull request by riverar**

### CODE REVIEW

**Review by mikematteson — APPROVED** [review]
Thanks for your contribution! We appreciate your help in catching and fixing this typo.

**Comment by normesta** [comment]
@riverar It appears that this contribution was overwritten at some point in the past. Sorry for the confusion. I see that you corrected a typo. I could go ahead and correct it myself, but I'd like your avatar to appear as a contributor. If you would like that as well, would you please resubmit that correction to the doc? I'll accept the pull request and make sure that it makes it onto the live site.

**Comment by riverar** [comment]
@normesta Hm, I'm not seeing the typo here https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-extensions.md. Did I miss something?

**Comment by normesta** [comment]
Hello, scroll down to the heading "Start a Win32 process from a Universal Windows Platform (UWP) app" and the typo appears as "<xtension Category". Please add the "E" and submit a PR. After I merge, and the topic publishes, your avatar will appear on the topic. Thx!

**Comment by riverar** [comment]
All set.

**Pull request merged**
