### PR TITLE
Modified according to documentation

### PR DESCRIPTION
**Pull request by ghost**
Hi, I have modified in a correct format....

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @hickeys - Could you review the proposed updates? Note that the original version aligns with the [Microsoft Writing Style Guide](https://docs.microsoft.com/style-guide/welcome/).

**Comment by ghost** [comment]
I have changed in middle of line to small word to Capital word..............and after doing that it looks good and check in Files changed section.

**Comment by PRMerger12** [comment]
@chinna98 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by hickeys** [comment]
@chinna98 I appreciate your taking the time to create this PR. Microsoft uses sentence casing for headers, as described [here](https://docs.microsoft.com/en-us/style-guide/capitalization). I'm going to close this PR, but please don't hesitate to open another in the future if you see an opportunity!

**Pull request closed without merging**
