### PR TITLE
M39322: Fixing typo B=binding/binding

### PR DESCRIPTION
**Pull request by v-maudel**
Translator has reported possible source content issue. 
Description: B=binding shopuld be binding

### CODE REVIEW

**Comment by PRMerger10** [comment]
@v-maudel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
Confirmed typo fix. Thanks.

**Comment by v-maudel** [comment]
Thanks @jborsecnik, can you please merge it? I don't have merge access to this repo. 
Regards.

**Comment by jborsecnik** [comment]
Yes, thanks.

**Pull request merged**
