### PR TITLE
Updating content and getting back in sync with main page

### PR DESCRIPTION
**Pull request by crutkas**
Adjusting links and language back with the main readme.

Also adding in exe args

### CODE REVIEW

**Comment by PRMerger12** [comment]
@crutkas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by mattwojo — APPROVED** [review]
Looks great!

**Comment by PRMerger8** [comment]
@mattwojo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattwojo** [comment]
Resolves https://github.com/MicrosoftDocs/windows-uwp/issues/3532

**Pull request merged**
