### PR TITLE
FAQ MD to YML Conversions - Pilot

### PR DESCRIPTION
**Pull request by cmcclister**
See https://dev.azure.com/ceapex/CPS/_workitems/edit/374411

### CODE REVIEW

**Comment by PRMerger14** [comment]
@v-chmccl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by cmcclister** [comment]
Hi @Khairunj I have no way of previewing my changes: https://review.docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/faq?branch=pr-en-us-2969. cc @stevewhims

**Review by stevewhims — APPROVED** [review]
This looks good to me as far as I can tell (not being familiar with the new format). :)

Thank you!

**Comment by stevewhims** [comment]
> Hi @Khairunj I have no way of previewing my changes: https://review.docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/faq?branch=pr-en-us-2969. cc @stevewhims

It's possible that your branch just hasn't finished building yet. Wouldn't you expect to review this branch at https://review.docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/faq?branch=faq-conversion? I'm not sure what the pr-en-us-2969 part is in the url above.

Oh, another thing is that this PR is in the public repo. The private repo (windows-uwp-pr) is where I do my work, and that's where I can see my stuff in preview. I'm actually not even sure whether previews are built in this public repo. Just a thought.

**Comment by ktoliver** [comment]
Hi @cmcclister - As @stevewhims points out, this pull request was opened in the public repo. This content has a private repo that has a staging environment. Would you submit the updates in a new PR in the private repo? We'll close this PR. Thanks!

**Comment by cmcclister** [comment]
Closing and will apply these changes to the private repo.

**Comment by ktoliver** [comment]
(The "review.docs.microsoft.com" domain refers to the Docs staging environment, and it isn't available in a public repository.)

**Pull request closed without merging**
