### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by asklar**
Supersedes #3868

- remove Facebook mention
- followup from offline discussion about winui3

### CODE REVIEW

**Comment by PRMerger10** [comment]
@asklar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by asklar** [comment]
@MatchaMatch fyi

**Comment by Jak-MS** [comment]
@QuinnRadich 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by QuinnRadich** [comment]
> @QuinnRadich
> 
> Can you review this PR?
> 
> IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.
> 
> #label:"aq-pr-triaged" @MicrosoftDocs/public-repo-pr-review-team

I believe there are a few pending changes coming here - we've discussed in an email thread.

**Comment by PRMerger7** [comment]
@asklar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by danroth27 — COMMENTED** [review]
Looks good

**Pull request merged**
