### PR TITLE
Clarify collection bindings

### PR DESCRIPTION
**Pull request by citelao**
C++/CX `Vector` was linking to the wrong place, and the table did not mention builtin C++/WinRT methods. I was also confused about `Platform::Collections::Vector` and added some clarifying text to the table.

Thanks!

### CODE REVIEW

**Comment by jborsecnik** [comment]
@MikeJacobs, can you review this PR? Thanks.

**Comment by jborsecnik** [comment]
@mijacobs, can you review this PR? Thanks.

**Comment by PRMerger10** [comment]
@citelao : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]

**Comment by stevewhims** [comment]
Thanks, @citelao! It's safe for you to delete your working branch now.

**Comment by citelao** [comment]
Thanks!

**Pull request merged**
