### PR TITLE
Update the-app-certification-process.md

### PR DESCRIPTION
**Pull request by ashwin-84**
1.    Removed 'Preprocessing' section 	
2.     Enhanced silent install section to include start menu, std user acct , Publisher name, lang, Clean un-install
2.	Updated malware test to include call out for Defender or other Antivirus
3.	Separated out Privacy policy 
4.	Content policy – add a blurb to link out to content policies section
5.	Removed publishing section since it was redundant

### CODE REVIEW

**Comment by PRMerger20** [comment]
@ashwin-84 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @ashwin-84 - This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. We can keep this PR open for review and merge, but would you make future content updates in the private repo? Thank you!

Let me know if you need information about working in the private repo; I can send it to you via email. Thanks.

**Comment by ktoliver** [comment]
We'll move the commit to the private repo at the PM contributor's request. I'll post here when the new PR is created.

**Comment by ktoliver** [comment]
The commit has been moved to a new pull request in the private repo, where it will merge from. We'll close this PR. Thanks.

https://github.com/MicrosoftDocs/windows-uwp-pr/pull/1822 (internal link)

**Pull request closed without merging**
