### PR TITLE
PowerToys text improvements

### PR DESCRIPTION
**Pull request by Jay-o-Way**
- basic spelling/grammar/etc.
- @yuyoyuppe input from https://github.com/microsoft/PowerToys/issues/20438
- @damienleroy added reference to your project 🙂

> **Note**
> Only focussed on 3 files of the new modules

### CODE REVIEW

**Comment by Jay-o-Way** [comment]
PTAL @yuyoyuppe

**Review by yuyoyuppe — APPROVED** [review]

**Comment by Jay-o-Way** [comment]
@mattwojo ready for now 🙂

**Review by mattwojo — APPROVED** [review]
Looks good!

**Comment by mattwojo** [comment]
#sign-off

**Comment by jborsecnik** [comment]
@mattwojo, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Jay-o-Way** [comment]
@jborsecnik didn't he already do that?

**Pull request merged**
