### PR TITLE
Updated Powertoys available languages list

### PR DESCRIPTION
**Pull request by peterscott-ni**
Added English to list

### CODE REVIEW

**Comment by PRMerger13** [comment]
@peterscott-ni : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@peterscott-ni : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by noraa-junker — APPROVED** [review]
LGTM

**Review by mattwojo — APPROVED** [review]

**Pull request merged**
