### PR TITLE
Update upgrade.md

### PR DESCRIPTION
**Pull request by jonas-lomholdt**
Fix typo.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@jonas-lomholdt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ktoliver** [comment]
As revised, grammatically, "them" seems to refer to "applications that have updates." Would it be accurate to instead say, "the Windows Package Manager will look for all applications that have updates available and attempt to install _the updates_"?

Thanks.
-PR review team

**Comment by jonas-lomholdt** [comment]
Sorry my English grammar is not on point. Your idea sounds good @ktoliver .

**Comment by PRMerger3** [comment]
@jonas-lomholdt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks @jonas-lomholdt. We'll merge this typo fix. Thanks for submitting it.

**Pull request merged**
