### PR TITLE
Change the word C++/WinRT to C#/WinRT in C# example

### PR DESCRIPTION
**Pull request by jaigak**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@Jaiganeshkumaran : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by stevewhims** [comment]
It's not just that text that needs to change, the link is pointing to a C++/WinRT topic. I don't have any context around this content, so deferring to the writer-owner. But yes it does seem inconsistent to be linking to info about C++/WinRT when the example is in the context of a .cs (C#) file.

Thanks!
Steve

**Comment by mcleanbyron** [comment]
Reassigning to the content owner for this article.

**Comment by ktoliver** [comment]
The content has been moved or reconfigured since the pull request was opened. The pull request can't be merged in, so we'll close it. Thanks.

**Pull request closed without merging**
