### PR TITLE
Update awake.md

### PR DESCRIPTION
**Pull request by florianmulatz**
The Value to change is customTrayTimes not tray_times anymore

### CODE REVIEW

**Comment by Court72** [comment]
@mattwojo

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by crutkas** [comment]
@dend to verify, if he signs off i'm good

**Comment by dend** [comment]
#sign-off

**Comment by mattwojo** [comment]
Thanks for this update and contribution @florianmulatz! Merged.

**Pull request merged**
