### PR TITLE
Updating Deprecation Notice

### PR DESCRIPTION
**Pull request by mapalko**
This feature is planned for deprecation in the second half of 2019. Updating this date in our documentation.

### CODE REVIEW

**Comment by garycentric** [comment]
@mapalko , @hickeys : The updated note has a redundant "the". Otherwise, this PR **passed** the acceptance checklist. Please evaluate further and approve/complete the PR if appropriate. Thanks!

**Comment by mapalko** [comment]
@beneluxboy  and @hickeys, I've updated the commit to remove the redundant work in the edit.

**Comment by mapalko** [comment]
@beneluxboy and @hickeys can you merge this request?

**Comment by mapalko** [comment]
@hickeys can you review and merge this request?

**Comment by mapalko** [comment]
@beneluxboy can you help with approving and merging this?

**Comment by mapalko** [comment]
@beneluxboy @hickeys, please review this change.

**Comment by PRMerger12** [comment]
@mapalko : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by hickeys — APPROVED** [review]

**Pull request merged**
