### PR TITLE
Usage of a nonexistent parameter

### PR DESCRIPTION
**Pull request by xLUDIOx**
There is no _window_ parameter or field in the scope of the **GetAppWindowForCurrentWindow** method. And looking at the C++ sample _this_ is the correct parameter to pass to **WinRT.Interop.WindowNative.GetWindowHandle**.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@xLUDIOx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Resolved the merge conflict (which might have implications for the proposed change).

@rkarman Could you review the pull request? Thanks.

**Review by rkarman — APPROVED** [review]
This looks good and should have been the case from the beginning. :) Thank you for finding this and providing a fix.

**Pull request merged**
