### PR TITLE
Do not use floats to store currencies.

### LINKED ISSUE #2403: Floating point types should not be used to store currency values
Floating point types can't store all values in the range x.nn. Using a float to store a bank account balance is an example of what not to do. See, for example:
http://wiki.c2.com/?FloatingPointCurrency

It's just an example here, but example code is often how programmers learn how to write production code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 565e1bd5-9e15-fc88-8ccc-05d09cbde209
* Version Independent ID: 63b7ce5c-d2e7-d742-4fbd-b9729595a797
* Content: [Author events in C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-events)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/author-events.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/author-events.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

### PR DESCRIPTION
**Pull request by davidmatson**
Switch the sample from a bank account to a thermometer.

Fixes #2403.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@davidmatson : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by davidmatson** [comment]
@stevewhims - I switched the sample to a thermometer as I believe you suggested via email a while back. Let me know what you think. Thanks!

**Comment by PRMerger15** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]
LGTM!

**Pull request merged**
