### PR TITLE
Fix and improve grammar

### PR DESCRIPTION
**Pull request by SamHobbsOrg**
The word "different" is misused so much that many people are unfamiliar with the proper use. I made some other fixes and improvements that I hope are okay. There was one duplication that I found. I hope it is appropriate to replace "3rd" with "third".

### CODE REVIEW

**Comment by garycentric** [comment]
@eliotcowley  @SamHobbsOrg : The PR **passed** the acceptance checklist. Please evaluate further and approve/complete the PR if appropriate. Thanks!

My editorial opinion about these changes follows...

**Line 3:** *Describes* replacing *Learn* seems fine, though *Learn* might be in place to describe what the reader would gain from the topic.
**Line 11:** Replacing *different* would definitely be an improvement. (I would choose *multiple*.) Beyond that, either version seems okay.
**Line 28:** Either the original or the revision seem okay. I prefer *Third*, and I would hyphenate *Third-party*.
**Line 34:** Either the original or the revision seem fine, though *expose* seems like the more conventional term for this type of context.
**Line 60:** Yes, the hyphen properly makes a compound word of the adjective.
**Line 72:** Either the original or the revision seem okay (though it's not easy to see what changed). Eliot may have another opinion.
**Line 76:** Not much difference between the two, and either is fine. Eliot may have another opinion.
**Line 91:** Yes, this should be either "other... apps" or "another... app".
**Line 93:** Yes, the comma after "web services" should be deleted.
**Line 109:** No changes in this line that I can discern.

**Comment by SamHobbsOrg** [comment]
Line 3: It is like the difference between teacher and student. A teacher teaches and a student learns. In this context describes is synonymous with teaches.
Line 11: Yes, either many or multiple.
Line 28: Yes, third-party should be hyphenated.
Line 72: Yes, the scope of the modification got expanded significantly. I changed "that are used" to "for use" and I changed "different" to "various".
Line 76: Another unnecessarily large amount of text in the differences. I changed "you're looking" to "you need". I think that "you need" is more formal. There are many alternatives that would be good.
Line 109: I don't know what happened there. Perhaps there is a difference in the number of trailing spaces.

**Comment by SamHobbsOrg** [comment]
Oh, and "learn" implies a tutorial or something else that is intended to teach. In other words, saying that someone can learn from something implies it is not documentation. A critical difference between documentation and educational material is that documentation should be complete and precise whereas it is assumed that educational material omits details and complications for the purpose of making the material easier to understand.

**Review by eliotcowley — APPROVED** [review]
Approved after minor edit, appreciate the feedback.

**Pull request merged**
