### PR TITLE
Delete twitter contest page

### PR DESCRIPTION
**Pull request by noraa-junker**
Related issue: #3638

cc: @mattwojo

### CODE REVIEW

**Comment by PRMerger19** [comment]
@Aaron-Junker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by noraa-junker** [comment]
@mattwojo Could you approve this PR, so it can get merged?

**Comment by mattwojo** [comment]
Thanks @Aaron-Junker!

**Review by mattwojo — APPROVED** [review]

**Pull request merged**
