### PR TITLE
[PowerToys] Docs update for activation command change

### PR DESCRIPTION
**Pull request by htcfreek**
Docs update for changes in PR https://github.com/microsoft/PowerToys/pull/19593 (issue https://github.com/microsoft/PowerToys/issues/18490).
- Updating keyword for `Time and Date`
- Adding a hint about conflicting keywords

image

**Note: Please wait with merging until the approval from @jaimecbernardo or @crutkas !!**

### CODE REVIEW

**Comment by PRMerger4** [comment]
@htcfreek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@htcfreek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@mattwojo 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by htcfreek** [comment]
@jaimecbernardo 
Please don't forget to review.

**Review by jaimecbernardo — APPROVED** [review]
LGTM! Thanks a lot for the contribution and for pinging! :)

**Comment by htcfreek** [comment]
Please merge this PR in.

**Review by mattwojo — APPROVED** [review]

**Pull request merged**
