### PR TITLE
Update screen-capture.md

### PR DESCRIPTION
**Pull request by ryanmajidi**
testing devlang fix

#hold-off

### CODE REVIEW

**Comment by PRMerger13** [comment]
@ryanmajidi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@ryanmajidi PMs should work in the private repo. Will you make future content updates in the private repo? Thanks.

@drewbatgit Would you review the proposed update to your article? Thanks.

**Review by drewbatgit — APPROVED** [review]

**Comment by drewbatgit** [comment]
#sign-off

**Comment by ktoliver** [comment]
Thanks.

**Pull request merged**
