### PR TITLE
Edited the `MSIX Package` path and `Upload app` path ci-for-winui3.md

### PR DESCRIPTION
**Pull request by CosmicPredator**
- Changed the MSIX Package Path to `${{ github.workspace }}\\Packages` for WinUI3 Packaged MSIX Workflow.
- Changed the "Upload app" Path to `${{ github.workspace }}\\bin` for WinUI3 Unpackaged App Workflow.

### CODE REVIEW

**Comment by Court72** [comment]
@stevewhims

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by stevewhims** [comment]
> @stevewhims
> 
> Can you review the proposed changes?
> 
> When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.
> 
> #label:"aq-pr-triaged" @MicrosoftDocs/public-repo-pr-review-team

It's up to you, but there's no need to leave these messages, btw. PRMerger sees to it that I'm made aware of the PR, and I don't need the sign off tag.

**Review by stevewhims — CHANGES_REQUESTED** [review]
We mention (in a Note in the topic) that if env.Solution_Name isn't working, you can replace it with github.workspace. So I think the topic is ok as-is. If env.Solution_Name is demonstrably the wrong approach (it was what was suggested by the SME who wrote this topic), then I'll be happy to change it, and remove the Note.

**Comment by stevewhims** [comment]
Closing, as per my comment above.

Thanks!
-Steve

**Comment by CosmicPredator** [comment]
> Closing, as per my comment above.
> 
> Thanks!
> -Steve

Actually, I tested the CI Workflow with different types of solutions, no folder with name `solution_name//bin` is created and it's not the right way as you know. So the `github.workspace` is the only approach to save and upload artifacts @stevewhims .

**Pull request closed without merging**
